# Generated by Django 3.2.4 on 2021-06-29 16:19

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dora.structures.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        validators=[dora.structures.models.validate_siret],
                        verbose_name="Siret",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("short_desc", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("full_desc", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("ressources_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=10)),
                ("faq_url", models.URLField(blank=True)),
                ("contact_form_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("postal_code", models.CharField(max_length=5)),
                ("city_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("has_solutions", models.BooleanField()),
                (
                    "solutions_themes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("MO", "Mobilité"),
                                ("HO", "Logement – Hébergement"),
                                ("CC", "Garde d'enfant"),
                                ("OT", "Autre"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "solutions_kinds",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "MK",
                                    "Solutions matérielle (ex : mise à disposition local, garde d’enfant ponctuelle, …)",
                                ),
                                ("FK", "Solution financière"),
                                ("SK", "Solution d’accompagnement"),
                            ],
                            max_length=2,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "other_themes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
