# Generated by Django 3.2.5 on 2021-08-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0003_auto_20210726_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="ape",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="structure",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="address1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="structure",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="structure",
            name="city_code",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="structure",
            name="has_services",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="structure",
            name="postal_code",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
