# Generated by Django 3.2.5 on 2021-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0004_auto_20210804_1530"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
