# Generated by Django 3.2.5 on 2021-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0007_auto_20210813_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="address1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="structure",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="structure",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="structure",
            name="postal_code",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="structure",
            name="short_desc",
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name="structure",
            name="typology",
            field=models.CharField(
                choices=[
                    ("PE", "Pôle emploi"),
                    ("CAP_EMPLOI", "CAP emploi"),
                    ("ML", "Mission locale"),
                    ("DEPT", "Service social du conseil départemental"),
                    (
                        "SPIP",
                        "SPIP — Service pénitentiaire d'insertion et de probation",
                    ),
                    ("PJJ", "PJJ — Protection judiciaire de la jeunesse"),
                    (
                        "CCAS",
                        "CCAS — Centre communal d'action sociale ou centre intercommunal d'action sociale",
                    ),
                    ("PLIE", "PLIE — Plan local pour l'insertion et l'emploi"),
                    ("CHRS", "CHRS — Centre d'hébergement et de réinsertion sociale"),
                    (
                        "CIDFF",
                        "CIDFF — Centre d'information sur les droits des femmes et des familles",
                    ),
                    ("PREVENTION", "Service ou club de prévention"),
                    (
                        "AFPA",
                        "AFPA — Agence nationale pour la formation professionnelle des adultes",
                    ),
                    ("PIJ_BIJ", "PIJ-BIJ — Point/Bureau information jeunesse"),
                    ("CAF", "CAF — Caisse d'allocation familiale"),
                    ("CADA", "CADA — Centre d'accueil de demandeurs d'asile"),
                    ("ASE", "ASE — Aide sociale à l'enfance"),
                    ("CAVA", "CAVA — Centre d'adaptation à la vie active"),
                    ("CPH", "CPH — Centre provisoire d'hébergement"),
                    ("CHU", "CHU — Centre d'hébergement d'urgence"),
                    (
                        "OACAS",
                        "OACAS — Structure porteuse d'un agrément national organisme d'accueil communautaire et d'activité solidaire",
                    ),
                    ("EI", "SIAE — Entreprise d'insertion"),
                    ("AI", "SIAE — Association intermédiaire"),
                    ("ACI", "SIAE — Atelier chantier d'insertion"),
                    (
                        "ACIPHC",
                        "SIAE — Atelier chantier d'insertion premières heures en chantier",
                    ),
                    ("ETTI", "SIAE — Entreprise de travail temporaire d'insertion"),
                    (
                        "EITI",
                        "SIAE — Entreprise d'insertion par le travail indépendant",
                    ),
                    (
                        "GEIQ",
                        "SIAE — Groupement d'employeurs pour l'insertion et la qualification",
                    ),
                    ("EA", "SIAE — Entreprise adaptée"),
                    ("EATT", "SIAE — Entreprise adaptée de travail temporaire"),
                    ("OTHER", "Autre"),
                ],
                max_length=10,
            ),
        ),
    ]
