# Generated by Django 3.2.5 on 2021-09-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0010_auto_20210918_1241"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="structuremember",
            options={"verbose_name": "Membre"},
        ),
    ]
