# Generated by Django 3.2.5 on 2021-09-20 09:36

from django.db import migrations, models

import dora.structures.models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0011_auto_20210920_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="code_safir_pe",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                unique=True,
                validators=[dora.structures.models.validate_safir],
                verbose_name="Code Safir Pole Emploi",
            ),
        ),
    ]
