# Generated by Django 3.2.5 on 2021-09-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0012_structure_code_safir_pe"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DORA", "Équipe DORA"),
                    ("ITOU", "Import ITOU"),
                    ("PORTEUR", "Porteur"),
                    ("PE", "API Référentiel Agence PE"),
                ],
                max_length=12,
            ),
        ),
    ]
