# Generated by Django 3.2.5 on 2021-09-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0013_structure_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="department",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
