# Generated by Django 3.2.5 on 2021-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0015_auto_20210920_1545"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="structuremember",
            name="unique_user_structure",
        ),
        migrations.AddConstraint(
            model_name="structuremember",
            constraint=models.UniqueConstraint(
                fields=("user", "structure"), name="structures_unique_user_by_structure"
            ),
        ),
    ]
