# Generated by Django 3.2.8 on 2021-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0016_auto_20210929_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="department",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
