# Generated by Django 3.2.8 on 2021-10-06 12:45

from django.db import migrations


def fix_departments(apps, schema_editor):
    Structure = apps.get_model("structures", "Structure")
    for structure in Structure.objects.all():
        if structure.department == "97":
            structure.department = structure.city_code[:3]
            structure.save()


def revert_fix(apps, schema_editor):
    Structure = apps.get_model("structures", "Structure")
    for structure in Structure.objects.all():
        if len(structure.department) == 3:
            structure.department = structure.city_code[:2]
            structure.save()


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0017_alter_structure_department"),
    ]

    operations = [
        migrations.RunPython(fix_departments, revert_fix),
    ]
