# Generated by Django 3.2.8 on 2021-10-06 15:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0018_fix_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuremember",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
