# Generated by Django 3.2.8 on 2021-10-06 15:10

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    StructureMember = apps.get_model("structures", "StructureMember")
    for row in StructureMember.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0019_structuremember_add_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
