# Generated by Django 3.2.8 on 2021-10-06 15:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0020_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuremember",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
