# Generated by Django 3.2.8 on 2021-10-06 15:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0021_auto_20211006_1710"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structuremember",
            name="id",
        ),
        migrations.AlterField(
            model_name="structuremember",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
