# Generated by Django 3.2.8 on 2021-10-06 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0022_auto_20211006_1714"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structuremember",
            old_name="uuid",
            new_name="id",
        ),
    ]
