# Generated by Django 3.2.8 on 2021-10-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0023_rename_uuid_structuremember_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuremember",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
