# Generated by Django 3.2.8 on 2021-10-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0024_structuremember_is_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuremember",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
    ]
