# Generated by Django 3.2.8 on 2021-10-07 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0025_alter_structuremember_is_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuremember",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
