# Generated by Django 3.2.8 on 2021-10-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0026_structuremember_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="is_antenna",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="structure",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DORA", "Équipe DORA"),
                    ("ITOU", "Import ITOU"),
                    ("PORTEUR", "Porteur"),
                    ("PE", "API Référentiel Agence PE"),
                    ("BI", "Invitations en masse"),
                ],
                db_index=True,
                max_length=12,
            ),
        ),
    ]
