# Generated by Django 3.2.8 on 2021-12-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0029_alter_structure_typology"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structuremember",
            old_name="is_valid",
            new_name="has_accepted_invitation",
        ),
    ]
