# Generated by Django 3.2.8 on 2021-12-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0030_rename_is_valid_structuremember_has_accepted_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuremember",
            name="has_been_accepted_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
