# Generated by Django 3.2.11 on 2022-01-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structures", "0031_auto_20220105_1925"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="structureputativemember",
            options={
                "verbose_name": "Membre Potentiel",
                "verbose_name_plural": "Membres Potentiels",
            },
        ),
        migrations.RenameField(
            model_name="structureputativemember",
            old_name="will_be_admin",
            new_name="is_admin",
        ),
        migrations.AlterField(
            model_name="structureputativemember",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="putative_membership",
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="structureputativemember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="putative_membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
