# Generated by Django 3.2.12 on 2022-03-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0033_alter_structure_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureSource2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StructureTypology2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="structure",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DORA", "Équipe DORA"),
                    ("ITOU", "Import ITOU"),
                    ("PORTEUR", "Porteur"),
                    ("PE", "API Référentiel Agence PE"),
                    ("BI", "Invitations en masse"),
                    ("COL", "Suggestion collaborative"),
                ],
                db_index=True,
                default="",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="typology",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "Associations de chômeurs"),
                    (
                        "ACI",
                        "Structures porteuses d’ateliers et chantiers d’insertion (ACI)",
                    ),
                    (
                        "ACIPHC",
                        "SIAE — Atelier chantier d’insertion premières heures en chantier",
                    ),
                    (
                        "AFPA",
                        "Agence nationale pour la formation professionnelle des adultes (AFPA)",
                    ),
                    ("AI", "Associations intermédiaires (AI)"),
                    ("ASE", "Aide sociale à l’enfance (ASE)"),
                    ("ASSO", "Associations"),
                    ("CADA", "Centres d’accueil de demandeurs d’asile (CADA)"),
                    ("CAF", "Caisses d’allocation familiale (CAF)"),
                    ("CAP_EMPLOI", "Cap Emploi"),
                    ("CAVA", "Centres d’adaptation à la vie active (CAVA)"),
                    ("CC", "Communautés de Commune"),
                    ("CCAS", "Centres communaux d’action sociale (CCAS)"),
                    ("CD", "Conseils Départementaux (CD)"),
                    ("CHRS", "Centres d’hébergement et de réinsertion sociale (CHRS)"),
                    ("CHU", "Centres d’hébergement d’urgence (CHU)"),
                    ("CIAS", "Centres intercommunaux d’action sociale (CIAS)"),
                    (
                        "CIDFF",
                        "Centres d’information sur les droits des femmes et des familles (CIDFF)",
                    ),
                    ("CPH", "Centres provisoires d’hébergement (CPH)"),
                    ("CS", "Centre social"),
                    ("CT", "Collectivités territoriales"),
                    (
                        "DEETS",
                        "Directions de l’Economie, de l’Emploi, du Travail et des Solidarités (DEETS)",
                    ),
                    (
                        "DIPLP",
                        "Délégation interministérielles à la prévention et à la lutte contre la pauvreté",
                    ),
                    ("EA", "Entreprise adaptée (EA)"),
                    ("EATT", "Entreprise Adaptée (EATT)"),
                    ("EI", "Entreprises d’insertion (EI)"),
                    (
                        "EITI",
                        "Entreprises d’insertion par le travail indépendant (EITI)",
                    ),
                    ("EPCI", "Intercommunalité (EPCI)"),
                    ("ETTI", "Entreprises de travail temporaire d’insertion (ETTI)"),
                    (
                        "FAIS",
                        "Fédérations d’acteurs de l’insertion et de la solidarité",
                    ),
                    (
                        "GEIQ",
                        "Groupements d’employeurs pour l’insertion et la qualification (GEIQ)",
                    ),
                    ("ML", "Mission Locale"),
                    ("MQ", "Maison de quartier"),
                    ("MSA", "Mutualité Sociale Agricole"),
                    ("MSAP", "Maison de Service au Public (MSAP)"),
                    ("MUNI", "Municipalités"),
                    (
                        "OACAS",
                        "Structures agréées Organisme d’accueil communautaire et d’activité solidaire (OACAS)",
                    ),
                    ("OF", "Organisme de formations"),
                    ("OTHER", "Autre"),
                    ("PE", "Pôle emploi"),
                    ("PIJ_BIJ", "Points et bureaux information jeunesse (PIJ/BIJ)"),
                    ("PIMMS", "Point Information Médiation Multi Services (PIMMS)"),
                    ("PJJ", "Protection judiciaire de la jeunesse (PJJ)"),
                    ("PLIE", "Plans locaux pour l’insertion et l’emploi (PLIE)"),
                    ("PR", "Préfecture, Sous-Préfecture"),
                    ("RE", "Région"),
                    ("SCCD", "Services sociaux du Conseil départemental"),
                    ("SCP", "Services et clubs de prévention"),
                    (
                        "SPIP",
                        "Services pénitentiaires d’insertion et de probation (SPIP)",
                    ),
                    ("TL", "Tiers lieu & coworking"),
                    ("UDAF", "Union Départementale d’Aide aux Familles (UDAF)"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="source2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structures.structuresource2",
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="typology2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structures.structuretypology2",
            ),
        ),
    ]
