# Generated by Django 3.2.12 on 2022-03-16 11:43

from django.db import migrations


def rename_value(Model, old_value, new_value):
    Model.objects.filter(value=old_value).update(value=new_value)


def add_value(Model, value, label):
    Model.objects.get_or_create(value=value, defaults={"label": label})


def rename_enums(apps, schema_editor):
    StructureSource = apps.get_model("structures", "StructureSource")
    rename_value(StructureSource, "PE", "api-referentiel-agences-pole-emploi")
    rename_value(StructureSource, "DORA", "equipe-dora")
    rename_value(StructureSource, "ITOU", "plateforme-inclusion")
    rename_value(StructureSource, "BI", "invitations-masse")
    rename_value(StructureSource, "PORTEUR", "porteur")
    rename_value(StructureSource, "COL", "suggestion-collaborative")

    StructureTypology = apps.get_model("structures", "StructureTypology")
    rename_value(StructureTypology, "AC", "ASSO_CHOMEUR")
    rename_value(StructureTypology, "OTHER", "Autre")
    rename_value(StructureTypology, "PR", "PREF")
    rename_value(StructureTypology, "RE", "REG")
    rename_value(StructureTypology, "SCCD", "DEPT")
    rename_value(StructureTypology, "TL", "TIERS_LIEUX")

    #
    add_value(
        StructureTypology,
        "CAARUD",
        "CAARUD - Centre d'accueil et d'accompagnement à la réduction de risques pour usagers de drogues",
    )
    add_value(
        StructureTypology,
        "CSAPA",
        "CSAPA - Centre de soins, d'accompagnement et de prévention en addictologie",
    )
    add_value(StructureTypology, "DEPT", "Service social du conseil départemental")
    add_value(StructureTypology, "E2C", "E2C - École de la deuxième chance")
    add_value(
        StructureTypology,
        "EPIDE",
        "EPIDE - Établissement pour l'insertion dans l'emploi",
    )
    add_value(
        StructureTypology,
        "HUDA",
        "HUDA - Hébergement d'urgence pour demandeurs d'asile",
    )
    add_value(StructureTypology, "ODC", "Organisation délégataire d'un CD")
    add_value(StructureTypology, "OIL", "Opérateur d'intermédiation locative")
    add_value(StructureTypology, "OPCS", "Organisation porteuse de la clause sociale")
    add_value(StructureTypology, "PENSION", "Pension de famille / résidence accueil")
    add_value(StructureTypology, "PREVENTION", "Service ou club de prévention")
    add_value(
        StructureTypology,
        "RS_FJT",
        "Résidence sociale / FJT - Foyer de Jeunes Travailleurs",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0037_auto_20220308_1630"),
    ]

    operations = [
        migrations.RunPython(rename_enums, reverse_code=migrations.RunPython.noop),
    ]
