# Generated by Django 3.2.12 on 2022-03-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0037_auto_20220308_1630"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="contact_form_url",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="faq_url",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="has_services",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="ressources_url",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="twitter_url",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="youtube_url",
        ),
    ]
