# Generated by Django 3.2.12 on 2022-03-15 17:08

from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0038_auto_20220315_1602"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="is_antenna",
        ),
        migrations.AddField(
            model_name="structure",
            name="branch_id",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="structure",
            name="siret",
            field=models.CharField(
                max_length=14,
                null=True,
                unique=True,
                validators=[dora.core.validators.validate_siret],
                verbose_name="Siret",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.UniqueConstraint(
                fields=("branch_id", "parent"),
                name="structures_structure_unique_branch_by_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("siret__length", 14), ("siret__isnull", True), _connector="OR"
                ),
                name="structures_structure_valid_or_null_siren",
            ),
        ),
    ]
