# Generated by Django 3.2.12 on 2022-03-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0038_rename_ids"),
        ("structures", "0039_auto_20220315_1808"),
    ]

    operations = []
