# Generated by Django 3.2.12 on 2022-03-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0040_merge_0038_rename_ids_0039_auto_20220315_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="structures.structure",
            ),
        ),
    ]
