# Generated by Django 3.2.12 on 2022-03-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0042_auto_20220323_1850"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="geocoding_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
