# Generated by Django 4.0.4 on 2022-05-24 16:38

from django.db import migrations


def add_source(apps, schema_editor):
    StructureSource = apps.get_model("structures", "StructureSource")
    StructureSource.objects.create(value="dr-dt-pole-emploi", label="DR et DT PE")


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0043_structure_geocoding_score"),
    ]

    operations = [
        migrations.RunPython(add_source, reverse_code=migrations.RunPython.noop),
    ]
