# Generated by Django 4.0.6 on 2022-08-10 16:21

from django.conf import settings
from django.db import migrations
from django.utils import timezone

from dora.core.models import ModerationStatus


def init_moderation_status(apps, schema_editor):
    Structure = apps.get_model("structures", "Structure")
    LogItem = apps.get_model("core", "LogItem")
    User = apps.get_model("users", "User")
    structures = Structure.objects.all()
    structures.update(
        moderation_status=ModerationStatus.VALIDATED, moderation_date=timezone.now()
    )
    msg = f"Modération initiale\nNouveau statut de modération : {ModerationStatus.VALIDATED.label}"
    bot_user = User.objects.get(email=settings.DORA_BOT_USER)
    for structure in structures:
        LogItem.objects.create(structure=structure, user=bot_user, message=msg)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("structures", "0045_structure_moderation_date_and_more"),
        ("users", "0005_create_dora_bot_user"),
    ]

    operations = [
        migrations.RunPython(
            init_moderation_status, reverse_code=migrations.RunPython.noop
        )
    ]
