# Generated by Django 4.0.6 on 2022-08-10 16:21

from django.db import migrations

from dora.core.models import ModerationStatus


def init_moderation_status(apps, schema_editor):
    Structure = apps.get_model("structures", "Structure")
    Structure.objects.all().update(moderation_status=ModerationStatus.VALIDATED)


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0045_structure_moderation_status_structure_notes"),
    ]

    operations = [
        migrations.RunPython(
            init_moderation_status, reverse_code=migrations.RunPython.noop
        )
    ]
