# Generated by Django 4.0.6 on 2022-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0046_init_moderation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="modification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
