# Generated by Django 4.0.7 on 2022-09-13 15:37

from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0046_init_moderation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureNationalLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Label national",
            },
        ),
        migrations.AddField(
            model_name="structure",
            name="accesslibre_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[dora.core.validators.validate_accesslibre_url],
                verbose_name="URL accesslibre",
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="hours_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="osm_hours",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[dora.core.validators.validate_osm_hours_str],
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="other_labels",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="national_labels",
            field=models.ManyToManyField(
                blank=True, null=True, to="structures.structurenationallabel"
            ),
        ),
    ]
