# Generated by Django 4.0.7 on 2022-09-13 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "structures",
            "0048_add_national_labels",
        ),
    ]

    def add_national_labels(apps, _):
        StructureNationalLabel = apps.get_model("structures", "StructureNationalLabel")

        StructureNationalLabel.objects.create(
            value="action-logement", label="Action logement"
        )
        StructureNationalLabel.objects.create(value="afpa", label="AFPA")
        StructureNationalLabel.objects.create(value="agefiph", label="AGEFIPH")
        StructureNationalLabel.objects.create(
            value="aidants-connect", label="Aidants Connect"
        )
        StructureNationalLabel.objects.create(
            value="alliance-villes-emploi", label="Alliance villes emploi"
        )
        StructureNationalLabel.objects.create(value="aptic", label="APTIC")
        StructureNationalLabel.objects.create(
            value="banques-alimentaires", label="Banques alimentaires"
        )
        StructureNationalLabel.objects.create(
            value="campus-connecte", label="Campus connecté"
        )
        StructureNationalLabel.objects.create(value="cci", label="CCI")
        StructureNationalLabel.objects.create(
            value="chantier-ecole", label="Chantier école"
        )
        StructureNationalLabel.objects.create(value="cheops", label="Cheops")
        StructureNationalLabel.objects.create(value="coorace", label="Coorace")
        StructureNationalLabel.objects.create(value="cresus", label="Crésus")
        StructureNationalLabel.objects.create(value="croix-rouge", label="Croix rouge")
        StructureNationalLabel.objects.create(value="dihal", label="DIHAL")
        StructureNationalLabel.objects.create(
            value="ecoles-de-la-deuxieme-chance", label="Ecoles de la deuxième chance"
        )
        StructureNationalLabel.objects.create(value="emmaus", label="Emmaus")
        StructureNationalLabel.objects.create(value="envie", label="Envie")
        StructureNationalLabel.objects.create(value="epide", label="EPIDE")
        StructureNationalLabel.objects.create(
            value="fabrique-de-territoire", label="Fabrique de Territoire"
        )
        StructureNationalLabel.objects.create(
            value="federation-des-acteurs-de-la-solidarite",
            label="Fédération des acteurs de la solidarité",
        )
        StructureNationalLabel.objects.create(
            value="federation-des-entreprises-dinsertion",
            label="Fédération des entreprises d'insertion",
        )
        StructureNationalLabel.objects.create(value="geiq", label="GEIQ")
        StructureNationalLabel.objects.create(
            value="grandes-ecoles-du-numerique", label="Grandes écoles du numérique"
        )
        StructureNationalLabel.objects.create(value="inae", label="INAE")
        StructureNationalLabel.objects.create(
            value="la-ressourcerie", label="La ressourcerie"
        )
        StructureNationalLabel.objects.create(
            value="maisons-de-lemploi", label="Maisons de l'Emploi"
        )
        StructureNationalLabel.objects.create(value="mdph", label="MDPH")
        StructureNationalLabel.objects.create(
            value="mission-locale", label="Mission Locale"
        )
        StructureNationalLabel.objects.create(
            value="point-conseil-budget", label="Point conseil budget"
        )
        StructureNationalLabel.objects.create(
            value="point-justice", label="Points Justice"
        )
        StructureNationalLabel.objects.create(
            value="ressourceries", label="Ressourceries"
        )
        StructureNationalLabel.objects.create(
            value="restos-du-coeur", label="Restos du coeur"
        )
        StructureNationalLabel.objects.create(
            value="secours-populaire", label="Secours populaire"
        )
        StructureNationalLabel.objects.create(value="siao", label="SIAO")
        StructureNationalLabel.objects.create(value="unai", label="UNAI")
        StructureNationalLabel.objects.create(
            value="unaf", label="Union nationale de l'aide aux familles"
        )
        StructureNationalLabel.objects.create(
            value="unccas",
            label="Union nationale des centres communaux d'action sociale",
        )
        StructureNationalLabel.objects.create(
            value="60000-rebonds", label="60 000 rebonds"
        )
        StructureNationalLabel.objects.create(value="adie", label="Adie")
        StructureNationalLabel.objects.create(value="apec", label="APEC")
        StructureNationalLabel.objects.create(
            value="apels", label="APELS Agence Pour l'Education par Le Sport"
        )
        StructureNationalLabel.objects.create(
            value="apprentis-dauteuil", label="Apprentis d'Auteuil"
        )
        StructureNationalLabel.objects.create(value="bge", label="BGE")
        StructureNationalLabel.objects.create(value="cidff", label="CIDFF")
        StructureNationalLabel.objects.create(value="cnam", label="CNAM")
        StructureNationalLabel.objects.create(value="crepi", label="CREPI")
        StructureNationalLabel.objects.create(
            value="duo-for-a-job", label="Duo for a job"
        )
        StructureNationalLabel.objects.create(value="egee", label="EGEE")
        StructureNationalLabel.objects.create(
            value="espace-emploi-agric-arrco", label="Espace Emploi Agirc Arrco"
        )
        StructureNationalLabel.objects.create(value="face", label="Fondation FACE")
        StructureNationalLabel.objects.create(
            value="force-femmes", label="Force Femmes"
        )
        StructureNationalLabel.objects.create(
            value="france-active", label="France Active"
        )
        StructureNationalLabel.objects.create(
            value="grand-test-couveuse-dentreprise",
            label="Grand Test Couveuse d'entreprise",
        )
        StructureNationalLabel.objects.create(value="hup", label="H'UP")
        StructureNationalLabel.objects.create(
            value="initiative-france", label="Initiative France"
        )
        StructureNationalLabel.objects.create(value="konexio", label="Konexio")
        StructureNationalLabel.objects.create(
            value="la-cravate-solidaire", label="La Cravate Solidaire"
        )
        StructureNationalLabel.objects.create(
            value="les-premieres", label="Les Premières"
        )
        StructureNationalLabel.objects.create(value="linklusion", label="Linklusion")
        StructureNationalLabel.objects.create(value="nqt", label="NQT")
        StructureNationalLabel.objects.create(
            value="positive-planet", label="Positive Planet"
        )
        StructureNationalLabel.objects.create(value="proxite", label="Proxité")
        StructureNationalLabel.objects.create(
            value="reseau-entreprendre", label="Réseau Entreprendre"
        )
        StructureNationalLabel.objects.create(value="scconseil", label="SC Conseil")
        StructureNationalLabel.objects.create(value="simplon", label="Simplon")
        StructureNationalLabel.objects.create(value="sinca", label="SINGA")
        StructureNationalLabel.objects.create(
            value="snc", label="SNC - Solidarité Nouvelle Face au Chômage"
        )
        StructureNationalLabel.objects.create(
            value="sport-dans-la-ville", label="Sport Dans La Ville"
        )
        StructureNationalLabel.objects.create(
            value="tous-tes-possible", label="Tous Tes Possibles"
        )
        StructureNationalLabel.objects.create(
            value="tzcld", label="TZCLD - Territoire Zero Chomeur Longue Durée"
        )
        StructureNationalLabel.objects.create(value="unis-cite", label="Unis-Cité")
        StructureNationalLabel.objects.create(
            value="fede-pro-fem", label="Federation Professionnelle Pour les Femmes"
        )

    operations = [
        migrations.RunPython(
            add_national_labels, reverse_code=migrations.RunPython.noop
        ),
    ]
