# Generated by Django 4.0.8 on 2022-11-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0049_add_more_national_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="address1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="structure",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="structure",
            name="postal_code",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="structure",
            name="short_desc",
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
