# Generated by Django 4.0.8 on 2022-10-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0049_add_more_national_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="has_been_edited",
            field=models.BooleanField(default=False),
        ),
    ]
