# Generated by Django 4.0.8 on 2022-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0050_alter_structure_address1_alter_structure_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="structurenationallabel",
            options={
                "verbose_name": "Label national",
                "verbose_name_plural": "Labels nationaux",
            },
        ),
        migrations.AddField(
            model_name="structure",
            name="data_inclusion_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="has_been_edited",
            field=models.BooleanField(default=False),
        ),
    ]
