# Generated by Django 4.0.8 on 2022-10-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0050_structure_has_been_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="data_inclusion_id",
            field=models.TextField(blank=True),
        ),
    ]
