# Generated by Django 4.1.3 on 2023-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0051_alter_structurenationallabel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="quick_start_done",
            field=models.BooleanField(default=False),
        ),
    ]
