# Generated by Django 4.1.7 on 2023-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0053_structure_quick_start_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="data_inclusion_id",
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
