# Generated by Django 4.1.9 on 2023-05-16 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0054_alter_structure_data_inclusion_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="other_labels_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
    ]
