# Generated by Django 4.1.9 on 2023-05-16 12:05

from django.db import migrations


def split_other_labels(apps, _):
    Structure = apps.get_model("structures", "Structure")
    for structure in Structure.objects.exclude(other_labels=""):
        structure.other_labels_array = [
            label.strip() for label in structure.other_labels.split(",")
        ]
        print(structure.slug)
        structure.save()


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0055_structure_other_labels_array"),
    ]

    operations = [
        migrations.RunPython(
            split_other_labels, reverse_code=migrations.RunPython.noop
        ),
    ]
