# Generated by Django 4.1.9 on 2023-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0056_split_other_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="other_labels",
        ),
    ]
