# Generated by Django 4.1.9 on 2023-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0057_remove_structure_other_labels"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structure",
            old_name="other_labels_array",
            new_name="other_labels",
        ),
    ]
