# Generated by Django 4.1.9 on 2023-05-16 14:24

from django.db import migrations

from dora.admin_express.utils import get_clean_city_name
from dora.core.utils import code_insee_to_code_dept


def clean_city_names_and_dept(apps, _):
    Structure = apps.get_model("structures", "Structure")
    Structure.objects.all().update(city="")
    for structure in Structure.objects.exclude(city_code=""):
        structure.city = get_clean_city_name(structure.city_code)
        structure.department = code_insee_to_code_dept(structure.city_code)
        structure.save()


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0058_rename_other_labels_array_structure_other_labels"),
    ]

    operations = [
        migrations.RunPython(
            clean_city_names_and_dept, reverse_code=migrations.RunPython.noop
        ),
    ]
