# Generated by Django 4.1.9 on 2023-06-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0059_clean_city_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="data_inclusion_source",
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
