# Generated by Django 4.2.3 on 2023-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0060_structure_data_inclusion_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="disable_orientation_form",
            field=models.BooleanField(default=False),
        ),
    ]
