# Generated by Django 4.2.3 on 2023-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "structures",
            "0062_remove_structure_structures_structure_unique_branch_by_parent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="structureputativemember",
            name="last_invitation_email_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
