# Generated by Django 4.2.3 on 2023-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "structures",
            "0062_remove_structure_structures_structure_unique_branch_by_parent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="is_obsolete",
            field=models.BooleanField(default=False),
        ),
    ]
