# Generated by Django 4.2.11 on 2024-04-23 10:45

from django.db import migrations


def migrate_ft(apps, _):
    Structure = apps.get_model("structures", "Structure")
    StructureNationalLabel = apps.get_model("structures", "StructureNationalLabel")
    StructureTypology = apps.get_model("structures", "StructureTypology")

    # Typologie
    ft_typo, _ = StructureTypology.objects.get_or_create(
        value="FT", defaults={"label": "France Travail"}
    )
    Structure.objects.filter(typology__value="PE").update(typology=ft_typo)
    StructureTypology.objects.filter(value="PE").delete()

    # Labels nationaux
    ft_nl, _ = StructureNationalLabel.objects.get_or_create(
        value="france-travail", defaults={"label": "France Travail"}
    )

    for structure in Structure.objects.filter(national_labels__value="pole-emploi"):
        structure.national_labels.add(ft_nl)
    StructureNationalLabel.objects.filter(value="pole-emploi").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0063_structure_is_obsolete"),
    ]

    operations = [
        migrations.RunPython(migrate_ft, reverse_code=migrations.RunPython.noop),
    ]
