# Generated by Django 4.2.11 on 2024-03-23 13:44

from data_inclusion.schema import Typologie
from django.db import migrations


def migrate_typologies(apps, _):
    Structure = apps.get_model("structures", "Structure")
    di_values = [t.value for t in Typologie]
    for structure in Structure.objects.exclude(typology=None):
        if structure.typology.value not in di_values:
            print(structure.slug, structure.typology.value)
        else:
            structure.typo_di = structure.typology.value
            structure.save(force_update=True)


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0065_structure_typo_di"),
    ]

    operations = [
        migrations.RunPython(
            migrate_typologies, reverse_code=migrations.RunPython.noop
        ),
    ]
