# Generated by Django 4.2.11 on 2024-03-23 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0066_remove_structure_typology"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structure",
            old_name="typo_di",
            new_name="typology",
        ),
    ]
