# Generated by Django 4.2.11 on 2024-03-23 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0066_migrate_typologies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="typology",
        ),
    ]
