# Generated by Django 4.2.11 on 2024-05-02 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0068_rename_typo_di_structure_typology"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StructureTypology",
        ),
    ]
