# Generated by Django 4.2.12 on 2024-06-28 09:12

from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0069_delete_structuretypology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[dora.core.validators.validate_phone_number],
            ),
        ),
    ]
