# Generated by Django 4.2.12 on 2024-07-15 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structures", "0070_alter_structure_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="putative_members",
            field=models.ManyToManyField(
                related_name="putative_structure_set",
                through="structures.StructurePutativeMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
