# Generated by Django 4.2.15 on 2024-10-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0071_structure_putative_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Nom"),
        ),
    ]
