# Generated by Django 4.2.3 on 2023-07-11 08:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orientations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orientation",
            name="beneficiary_contact_preferences",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("TELEPHONE", "Téléphone"),
                        ("EMAIL", "E-mail"),
                        ("AUTRE", "Autre"),
                    ],
                    max_length=10,
                ),
                default=list,
                size=None,
                verbose_name="Préférences de contact",
            ),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="beneficiary_first_name",
            field=models.CharField(max_length=140, verbose_name="Prénom bénéficiaire"),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="beneficiary_last_name",
            field=models.CharField(max_length=140, verbose_name="Nom bénéficiaire"),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="prescriber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prescripteur",
            ),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="referent_email",
            field=models.EmailField(max_length=254, verbose_name="Courriel référent"),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="referent_first_name",
            field=models.CharField(max_length=140, verbose_name="Prénom référent"),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="referent_last_name",
            field=models.CharField(max_length=140, verbose_name="Nom référent"),
        ),
    ]
