# Generated by Django 4.2.3 on 2023-07-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orientations",
            "0002_alter_orientation_beneficiary_contact_preferences_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="original_service_name",
            field=models.CharField(
                default="", editable=False, max_length=140, verbose_name="Nom original"
            ),
        ),
    ]
