# Generated by Django 4.2.3 on 2023-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0003_orientation_original_service_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Motif de refus",
                "verbose_name_plural": "Motifs de refus",
            },
        ),
        migrations.AddField(
            model_name="orientation",
            name="rejection_reasons",
            field=models.ManyToManyField(
                blank=True,
                to="orientations.rejectionreason",
                verbose_name="Motifs de refus de l'orientation",
            ),
        ),
    ]
