# Generated by Django 4.2.3 on 2023-07-13 14:25

from django.db import migrations


def strip_cedex(apps, schema_editor):
    RejectionReason = apps.get_model("orientations", "RejectionReason")
    reasons = [
        {
            "value": "bénéficiaire-non-joignable",
            "label": "Bénéficiaire non joignable",
        },
        {
            "value": "bénéficiaire-absent",
            "label": "Bénéficiaire ne s’étant pas présenté à l’entretien",
        },
        {
            "value": "bénéficiaire-en-emploi",
            "label": "Bénéficiaire indisponible : en emploi",
        },
        {
            "value": "bénéficiaire-en-formation",
            "label": "Bénéficiaire indisponible : en formation",
        },
        {
            "value": "bénéficiaire-non-éligible",
            "label": "Bénéficiaire non éligible (ne répond pas aux pré-requis)",
        },
        {
            "value": "bénéficiaire-non-mobile",
            "label": "Bénéficiaire non mobile",
        },
        {
            "value": "bénéficiaire-non-intéressé",
            "label": "Bénéficiaire non intéressé",
        },
        {
            "value": "freins-périphériques",
            "label": "Un ou plusieurs freins périphériques empêchent le bénéficiaire de poursuivre",
        },
        {
            "value": "session-complète",
            "label": "Session complète",
        },
        {
            "value": "orientation-en-doublon",
            "label": "Orientation en doublon",
        },
        {
            "value": "autre",
            "label": "Autre (détails dans le message ci-dessous)",
        },
    ]

    for reason in reasons:
        RejectionReason.objects.create(value=reason["value"], label=reason["label"])


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0004_rejectionreason_orientation_rejection_reasons"),
    ]

    operations = [
        migrations.RunPython(strip_cedex),
    ]
