# Generated by Django 4.2.3 on 2023-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0006_sentcontactemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="last_reminder_email_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
