# Generated by Django 4.2.12 on 2024-05-08 14:59

from django.db import migrations, models

import dora.orientations.models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0008_orientation_di_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientation",
            name="query_expires_at",
            field=models.DateTimeField(
                default=dora.orientations.models._orientation_query_expiration_date,
                verbose_name="expiration du lien de la demande",
            ),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date de création"
            ),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="processing_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date de traitement"
            ),
        ),
        migrations.AlterField(
            model_name="orientation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OUVERTE", "Ouverte / En cours de traitement"),
                    ("VALIDÉE", "Validée"),
                    ("REFUSÉE", "Refusée"),
                ],
                default="OUVERTE",
                max_length=10,
                verbose_name="statut",
            ),
        ),
    ]
