# Generated by Django 4.2.12 on 2024-07-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orientations", "0009_orientation_query_expires_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orientation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("service", None),
                        models.Q(("di_service_id", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("service", None), _negated=True),
                        ("di_service_id", ""),
                    ),
                    _connector="OR",
                ),
                name="check_valid_service",
            ),
        ),
    ]
