# Generated by Django 3.2.5 on 2021-09-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rest_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={"verbose_name": "Token", "verbose_name_plural": "Tokens"},
        ),
        migrations.AddField(
            model_name="token",
            name="expiration",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_token",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
