# Generated by Django 4.1.7 on 2023-02-28 16:12

import random
from datetime import timedelta

from django.conf import settings
from django.db import migrations
from django.utils import timezone


def add_token_expiration(apps, _):
    for model_name in ["City", "EPCI", "Department", "Region"]:
        Token = apps.get_model("rest_auth", "Token")
        valid_tokens = Token.objects.filter(expiration=None)
        # Pour tous les tokens sans date d'expiration, on met une date entre +2j et
        # +IC_EXPIRATION_DELAY_DAYS au hasard afin d'éviter que tous les utilisateurs
        # soient invalidés en même temps.
        for token in valid_tokens:
            token.expiration = timezone.now() + timedelta(
                days=random.randint(2, settings.IC_EXPIRATION_DELAY_DAYS)
            )
            token.save(force_update=True)


class Migration(migrations.Migration):
    dependencies = [
        ("rest_auth", "0002_auto_20210914_1657"),
    ]

    operations = [migrations.RunPython(add_token_expiration, migrations.RunPython.noop)]
