# Generated by Django 4.2.10 on 2024-03-19 10:05


from django.db import migrations


def migrate_tokens(apps, _):
    User = apps.get_model("users", "User")
    DRFToken = apps.get_model("authtoken", "Token")

    for user in User.objects.exclude(auth_token=None):
        most_recent_token = user.auth_token.order_by("-created").first()
        DRFToken.objects.create(
            key=most_recent_token.key,
            user=most_recent_token.user,
            created=most_recent_token.created,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("rest_auth", "0005_remove_token_expiration"),
        ("users", "0005_create_dora_bot_user"),
    ]

    operations = [migrations.RunPython(migrate_tokens, migrations.RunPython.noop)]
