repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        name: Ruff (Flake8)
        args: [ --fix ]
      - id: ruff-format
        name: Ruff format (Black + isort)
        args: [ --check ]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        name: Sqlfluff (postgres)

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.18.1
    hooks:
      - id: ggshield
        language_version: python3
        stages: [ commit ]

  - repo: https://github.com/rtts/djhtml
    rev: '3.0.6'
    hooks:
      - id: djhtml
        types: [file]
        files: \.(html|mjml)$
        args: ["--tabwidth=2"]
