[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.pylint.main]
# Files or directories to be skipped. They should be base names, not paths.
ignore = ["CVS"]

# List of plugins (as comma separated values of python module names) to load,
# usually to register additional checkers.
load-plugins = "pylint_django,pylint_django.checkers.migrations"

# When enabled, pylint would attempt to guess common misconfiguration and emit
# user-friendly hints instead of false-positive error messages.
# suggestion-mode = true

[tool.pylint.basic]

[tool.pylint.classes]

[tool.pylint.design]

[tool.pylint.exceptions]

[tool.pylint.format]

[tool.pylint.imports]

[tool.pylint.logging]

[tool.pylint."messages control"]
disable = ["missing-function-docstring", "missing-module-doctstring", "missing-class-docstring"]

[tool.pylint.method_args]

[tool.pylint.refactoring]

[tool.pylint.reports]

[tool.pylint.similarities]

[tool.pylint.spelling]

[tool.pylint.string]

[tool.pylint.typecheck]

[tool.pylint.variables]
