[tool.pylint.main]
# Files or directories to be skipped. They should be base names, not paths.
ignore = ["CVS"]

# List of plugins (as comma separated values of python module names) to load,
# usually to register additional checkers.
load-plugins = "pylint_django,pylint_django.checkers.migrations"

# When enabled, pylint would attempt to guess common misconfiguration and emit
# user-friendly hints instead of false-positive error messages.
# suggestion-mode = true

[tool.pylint."messages control"]
disable = ["missing-function-docstring", "missing-module-doctstring", "missing-class-docstring"]

[tool.ruff]
ignore = ["E501", "E203"]
line-length = 88
# set to minimum compatibility with flake8, update / extend as needed
# see rules : https://docs.astral.sh/ruff/rules/
select = [
    "Q",  # flake8 quotes
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
]

[tool.ruff.isort]
known-first-party = ["dora"]
