[tool.ruff]
ignore = ["E501", "E203"]
line-length = 88
# Compatibilité minimale avec flake8, à faire évoluer si nécessaire
# voir les règles de lint : https://docs.astral.sh/ruff/rules/
select = [
    "Q",  # flake8 : quotes
    "F",  # pyflakes
    "E",  # pycodestyle : erreurs
    "W",  # pycodestyle : avertissements
    "I",  # isort
]

[tool.ruff.isort]
known-first-party = ["dora"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="config.settings"
python_files = ["test.py", "tests*.py", "test_*.py"]

# Note : la plupart des éléments de configuration de sqlfluff
# sont basés sur les recommandantions et usages de Data-Inclusion
[tool.sqlfluff.core]
dialect = "postgres"
sql_file_exts = ".sql"

[tool.sqlfluff.layout.type.alias_expression]
# Alignement vertical pour les aliases
# https://docs.sqlfluff.com/en/stable/layout.html#aligned-elements
spacing_before = "align"
# Aliases alignés dans la clause SELECT
align_within = "select_clause"
# Alignement des éléments entre parenthèses : 
align_scope = "bracketed"

# Pour les règles de sqlfluff, voir :  
# - https://docs.sqlfluff.com/en/stable/rules.html
# Pour les directives de configuration dans les fichiers : 
# - https://docs.sqlfluff.com/en/stable/configuration.html#in-file-configuration-directives
[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.functions]
extended_capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.literals]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.references.special_chars]
# Utiles pour les aliases de champs Metabase
additional_allowed_characters = "àéè '-"
