# Generated by Django 4.1.9 on 2023-06-29 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0003_abtestgroup_structureview_serviceview_searchview_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilisationevent",
            name="service_slug",
        ),
        migrations.RemoveField(
            model_name="mobilisationevent",
            name="structure_slug",
        ),
        migrations.RemoveField(
            model_name="serviceview",
            name="service_slug",
        ),
        migrations.RemoveField(
            model_name="serviceview",
            name="structure_slug",
        ),
        migrations.RemoveField(
            model_name="structureview",
            name="structure_slug",
        ),
    ]
