# Generated by Django 4.2.3 on 2023-07-18 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0095_remove_service_is_draft_remove_service_is_suggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orientations", "0006_sentcontactemail"),
        ("structures", "0060_structure_data_inclusion_source"),
        ("stats", "0004_remove_mobilisationevent_service_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrientationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "update_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEEDED", "Actualisation conseillée"),
                            ("NOT_NEEDED", "Service à jour"),
                            ("REQUIRED", "Actualisation exigée"),
                        ],
                        max_length=10,
                        verbose_name="Statut d'actualisation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "orientation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OUVERTE", "Ouverte / En cours de traitement"),
                            ("VALIDÉE", "Validée"),
                            ("REFUSÉE", "Refusée"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "orientation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orientations.orientation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.service",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
