# Generated by Django 4.2.3 on 2023-07-18 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0095_remove_service_is_draft_remove_service_is_suggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0005_orientationview"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilisationevent",
            name="service_source",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="La source de l'import de ce service",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="mobilisationevent",
            name="structure_source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="service_source",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="La source de l'import de ce service",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="structure_source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="searchview",
            name="num_di_results",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchview",
            name="num_di_results_top10",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="serviceview",
            name="service_source",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="La source de l'import de ce service",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="serviceview",
            name="structure_source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="structureview",
            name="structure_source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="DiServiceView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("structure_id", models.CharField(default="", max_length=255)),
                ("structure_name", models.CharField(default="", max_length=255)),
                (
                    "structure_department",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=3
                    ),
                ),
                ("service_id", models.CharField(default="", max_length=255)),
                ("service_name", models.CharField(default="", max_length=255)),
                ("source", models.CharField(default="", max_length=255)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
