# Generated by Django 4.2.3 on 2023-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_dimobilisationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceview",
            name="mobilisable",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Service mobilisable"
            ),
        ),
    ]
