# Generated by Django 4.2.3 on 2023-08-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_dimobilisationevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrientationContactBeneficiaryEvent",
            fields=[
                (
                    "orientationview_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stats.orientationview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("stats.orientationview",),
        ),
        migrations.CreateModel(
            name="OrientationContactServiceEvent",
            fields=[
                (
                    "orientationview_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stats.orientationview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("stats.orientationview",),
        ),
    ]
