# Generated by Django 4.2.3 on 2023-08-10 13:55

from django.conf import settings
from django.db import migrations, models


# Copie depuis : /dora-back/dora/services/serializers.py
# On se permet la copie pour assurer une continuité de comportement
def can_show_orientation_form(structure):
    for siren in settings.ORIENTATION_SIRENE_BLACKLIST:
        if structure.siret and structure.siret.startswith(siren):
            return False
    return not structure.disable_orientation_form


def is_mobilisable(service):
    beneficiaries_access_modes = [
        s
        for s in service.beneficiaries_access_modes.all().values_list(
            "value", flat=True
        )
    ]
    coach_orientation_modes = [
        s for s in service.coach_orientation_modes.all().values_list("value", flat=True)
    ]

    return (
        can_show_orientation_form(service.structure)
        and service.contact_email
        and (
            "envoyer-courriel" in coach_orientation_modes
            or "envoyer-fiche-prescription" in coach_orientation_modes
            or "envoyer-courriel" in beneficiaries_access_modes
        )
    )


def migrate_mobilisable_services(apps, schema_editor):
    ServiceView = apps.get_model("stats", "ServiceView")
    Service = apps.get_model("services", "Service")

    service_ids = [
        str(s["service_id"])
        for s in ServiceView.objects.distinct("service_id").values()
    ]
    services = (
        Service.objects.filter(id__in=service_ids)
        .select_related("structure")
        .prefetch_related(
            "beneficiaries_access_modes",
            "coach_orientation_modes",
        )
    )

    for service in services:
        service.mobilisable = is_mobilisable(service)
        # print(service.id, f"http://localhost:3000/services/{service.slug}", service.mobilisable)
        service.save()


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_dimobilisationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceview",
            name="mobilisable",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Service mobilisable"
            ),
        ),
        migrations.RunPython(
            migrate_mobilisable_services, reverse_code=migrations.RunPython.noop
        ),
    ]
