# Generated by Django 4.2.3 on 2023-09-05 08:43

from django.conf import settings
from django.db import migrations
from django.db.models import Q


def is_orientable(service):
    structure_blacklisted = False
    for siren in settings.ORIENTATION_SIRENE_BLACKLIST:
        if service.structure.siret and service.structure.siret.startswith(siren):
            structure_blacklisted = True

    return (
        not service.structure.disable_orientation_form
        and not structure_blacklisted
        and service.contact_email != ""
        and (
            service.coach_orientation_modes.filter(
                Q(value="envoyer-courriel") | Q(value="envoyer-fiche-prescription")
            ).exists()
            or service.beneficiaries_access_modes.filter(
                value="envoyer-courriel"
            ).exists()
        )
    )


def migrate_mobilisable_services(apps, schema_editor):
    ServiceView = apps.get_model("stats", "ServiceView")

    for serviceView in ServiceView.objects.exclude(service=None):
        serviceView.is_orientable = is_orientable(serviceView.service)
        serviceView.save()


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0008_serviceview_orientable"),
    ]

    operations = [
        migrations.RunPython(
            migrate_mobilisable_services, reverse_code=migrations.RunPython.noop
        ),
    ]
