# Generated by Django 4.2.3 on 2023-09-05 08:43

from django.conf import settings
from django.db import migrations
from django.db.models import Q

from dora.services.enums import ServiceStatus


def was_orientable(service_view):
    structure_blacklisted = False
    for siren in settings.ORIENTATION_SIRENE_BLACKLIST:
        if service_view.structure.siret and service_view.structure.siret.startswith(
            siren
        ):
            structure_blacklisted = True
            break
    return (
        service_view.status == ServiceStatus.PUBLISHED
        and not service_view.structure.disable_orientation_form
        and not structure_blacklisted
        and service_view.service.contact_email != ""
        and (
            service_view.service.coach_orientation_modes.filter(
                Q(value="envoyer-courriel") | Q(value="envoyer-fiche-prescription")
            ).exists()
            or service_view.service.beneficiaries_access_modes.filter(
                value="envoyer-courriel"
            ).exists()
        )
    )


def migrate_mobilisable_services(apps, schema_editor):
    ServiceView = apps.get_model("stats", "ServiceView")

    for serviceView in ServiceView.objects.exclude(service=None):
        serviceView.is_orientable = was_orientable(serviceView)
        serviceView.save()


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0008_serviceview_orientable"),
    ]

    operations = [
        migrations.RunPython(
            migrate_mobilisable_services, reverse_code=migrations.RunPython.noop
        ),
    ]
