# Generated by Django 4.2.5 on 2023-09-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0095_remove_service_is_draft_remove_service_is_suggestion"),
        ("stats", "0009_fill_is_orientable_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilisationevent",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="services.servicecategory"
            ),
        ),
        migrations.AddField(
            model_name="mobilisationevent",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="services.servicesubcategory"
            ),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="services.servicecategory"
            ),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="services.servicesubcategory"
            ),
        ),
        migrations.AddField(
            model_name="serviceview",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="services.servicecategory"
            ),
        ),
        migrations.AddField(
            model_name="serviceview",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="services.servicesubcategory"
            ),
        ),
    ]
