# Generated by Django 4.2.5 on 2023-09-27 13:49

from django.db import migrations


def freeze_categories(apps, schema_editor):
    MobilisationEvent = apps.get_model("stats", "MobilisationEvent")
    OrientationView = apps.get_model("stats", "OrientationView")
    ServiceView = apps.get_model("stats", "ServiceView")

    for AnalyticsModel in [MobilisationEvent, OrientationView, ServiceView]:
        for event in AnalyticsModel.objects.all():
            event.categories.set(event.service.categories.all())
            event.subcategories.set(event.service.subcategories.all())


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0010_mobilisationevent_categories_and_more"),
    ]

    operations = [
        migrations.RunPython(freeze_categories, reverse_code=migrations.RunPython.noop),
    ]
