# Generated by Django 4.2.5 on 2023-10-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0011_service_category_freeze"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimobilisationevent",
            name="search_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stats.searchview",
            ),
        ),
        migrations.AddField(
            model_name="diserviceview",
            name="search_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stats.searchview",
            ),
        ),
        migrations.AddField(
            model_name="mobilisationevent",
            name="search_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stats.searchview",
            ),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="search_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stats.searchview",
            ),
        ),
        migrations.AddField(
            model_name="serviceview",
            name="search_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stats.searchview",
            ),
        ),
    ]
