# Generated by Django 4.2.7 on 2024-02-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0013_searchview_results_slugs_top10"),
    ]

    operations = [
        migrations.AddField(
            model_name="orientationview",
            name="di_service_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="di_service_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="di_structure_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orientationview",
            name="is_di",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
