# Generated by Django 4.2.7 on 2024-02-08 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0014_orientationview_di_service_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimobilisationevent",
            name="ab_test_groups",
        ),
        migrations.RemoveField(
            model_name="mobilisationevent",
            name="ab_test_groups",
        ),
        migrations.DeleteModel(
            name="ABTestGroup",
        ),
    ]
