# Generated by Django 4.2.7 on 2024-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0103_savedsearch_location_kinds"),
        ("stats", "0015_remove_dimobilisationevent_ab_test_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchview",
            name="fee_conditions",
            field=models.ManyToManyField(
                blank=True, to="services.servicefee", verbose_name="Frais à charge"
            ),
        ),
        migrations.AddField(
            model_name="searchview",
            name="kinds",
            field=models.ManyToManyField(
                blank=True, to="services.servicekind", verbose_name="Type de service"
            ),
        ),
        migrations.AddField(
            model_name="searchview",
            name="location_kinds",
            field=models.ManyToManyField(
                blank=True,
                to="services.locationkind",
                verbose_name="Lieu de déroulement",
            ),
        ),
    ]
