# Generated by Django 4.2.10 on 2024-03-14 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0104_service_appointment_link"),
        ("structures", "0063_structure_is_obsolete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0016_searchview_fee_conditions_searchview_kinds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "update_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEEDED", "Actualisation conseillée"),
                            ("NOT_NEEDED", "Service à jour"),
                            ("REQUIRED", "Actualisation exigée"),
                        ],
                        max_length=10,
                        verbose_name="Statut d'actualisation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUGGESTION", "Suggestion"),
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "service_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="La source de l'import de ce service",
                        max_length=255,
                    ),
                ),
                ("is_di", models.BooleanField(db_index=True, default=False)),
                (
                    "recipient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[
                            ("beneficiary", "Bénéficiaire"),
                            ("professional", "Professionnel"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("di_structure_name", models.CharField(default="", max_length=255)),
                ("di_service_id", models.CharField(default="", max_length=255)),
                ("di_service_name", models.CharField(default="", max_length=255)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicecategory"
                    ),
                ),
                (
                    "search_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.searchview",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.service",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="services.servicesubcategory"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
