# Generated by Django 4.2.10 on 2024-04-30 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0063_structure_is_obsolete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0017_serviceshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureInfosView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_user_hash", models.CharField(blank=True, max_length=32)),
                ("is_logged", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_manager", models.BooleanField()),
                ("is_an_admin", models.BooleanField()),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompagnateur", "Accompagnateur"),
                            ("offreur", "Offreur"),
                            ("accompagnateur_offreur", "Accompagnateur et offreur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Activité principale de l'utilisateur",
                    ),
                ),
                ("is_structure_member", models.BooleanField()),
                ("is_structure_admin", models.BooleanField()),
                (
                    "structure_department",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                (
                    "structure_city_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Code INSEE de la structure",
                    ),
                ),
                (
                    "structure_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structures.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
