# Generated by Django 4.2.12 on 2024-06-28 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0018_structureinfosview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="structureinfosview",
            options={
                "verbose_name": "clic sur contacts de la structure",
                "verbose_name_plural": "clics sur contacts de la structure",
            },
        ),
    ]
