# Generated by Django 4.2.12 on 2024-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0019_alter_structureinfosview_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimobilisationevent",
            name="external_link",
            field=models.URLField(blank=True, null=True, verbose_name="lien externe"),
        ),
        migrations.AddField(
            model_name="mobilisationevent",
            name="external_link",
            field=models.URLField(blank=True, null=True, verbose_name="lien externe"),
        ),
    ]
