# Generated by Django 3.2.5 on 2021-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20210914_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_valid",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user's email address has been validate.",
                verbose_name="valid",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=140, verbose_name="name"),
        ),
    ]
