# Generated by Django 3.2.5 on 2021-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210918_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_valid",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user's email address has been validated.",
                verbose_name="valid",
            ),
        ),
    ]
