# Generated by Django 3.2.5 on 2021-09-20 09:57

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_bot_user(apps, _schema_editor):
    User = apps.get_model("users", "User")

    user = User.objects.create(
        email=settings.DORA_BOT_USER,
        name="DoraBot",
    )
    user.password = make_password(None)
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_is_valid"),
    ]

    operations = [
        migrations.RunPython(create_bot_user),
    ]
