# Generated by Django 3.2.8 on 2021-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_create_dora_bot_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=140, verbose_name="Prénom"),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="Nom de famille"
            ),
        ),
    ]
