# Generated by Django 3.2.11 on 2022-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bizdev",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l’utilisateur a les droits bizdev (valider les contributions…)",
                verbose_name="bizdev status",
            ),
        ),
    ]
