# Generated by Django 3.2.12 on 2022-03-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
            },
        ),
    ]
