# Generated by Django 4.0.6 on 2022-09-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ic_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Identifiant Inclusion Connect"
            ),
        ),
    ]
