# Generated by Django 4.1.3 on 2022-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0084_bookmark_bookmark_services_unique_bookmark"),
        ("users", "0011_user_ic_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarks",
            field=models.ManyToManyField(
                through="services.Bookmark", to="services.service"
            ),
        ),
    ]
