# Generated by Django 4.1.3 on 2022-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_notification_email_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
