# Generated by Django 4.1.6 on 2023-02-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_last_notification_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                default="",
                help_text="Département d'un coordinateur local",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_local_coordinator",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l’utilisateur est un coordinateur local",
                verbose_name="coordinateur local",
            ),
        ),
    ]
