# Generated by Django 4.1.3 on 2023-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_last_notification_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="extra_infos",
            field=models.JSONField(default=dict),
        ),
    ]
