# Generated by Django 4.1.7 on 2023-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_extra_infos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_local_coordinator",
            new_name="is_manager",
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                default="", help_text="Département d'un gestionnaire", max_length=3
            ),
        ),
    ]
