# Generated by Django 4.1.7 on 2023-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_rename_user_is_local_coordinator_user_is_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_bizdev",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l’utilisateur est un gestionnaire (de département)",
                verbose_name="gestionnaire",
            ),
        ),
    ]
