# Generated by Django 4.1.7 on 2023-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_user_is_bizdev_alter_user_is_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Département d'un gestionnaire",
                max_length=3,
            ),
        ),
    ]
