# Generated by Django 4.1.3 on 2023-04-19 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_remove_user_onboarding_actions_accomplished"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
