# Generated by Django 4.1.9 on 2023-06-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_remove_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="main_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accompagnateur", "Accompagnateur"),
                    ("offreur", "Offreur"),
                    ("accompagnateur_offreur", "Accompagnateur et offreur"),
                    ("autre", "Autre"),
                ],
                db_index=True,
                max_length=25,
                verbose_name="Activité principale de l'utilisateur",
            ),
        ),
    ]
