# Generated by Django 4.2.3 on 2023-08-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_user_main_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cgu_versions_accepted",
            field=models.JSONField(default=dict),
        ),
    ]
