# Generated by Django 4.2.3 on 2023-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_user_main_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cgu",
            field=models.JSONField(default=dict),
        ),
    ]
