# Generated by Django 4.2.3 on 2023-09-12 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_user_cgu_versions_accepted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_notification_email_sent",
            new_name="last_service_reminder_email_sent",
        ),
    ]
