# Generated by Django 4.2.3 on 2023-08-07 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_user_cgu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="cgu",
            new_name="cgu_versions_accepted",
        ),
    ]
