# Generated by Django 4.2.7 on 2024-02-01 10:03

import logging

import django.contrib.postgres.fields
from django.db import migrations, models

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    def update_departments_array(apps, schema_editor):
        User = apps.get_model("users", "user")
        if managers := User.objects.exclude(department="").filter(is_manager=True):
            logger.info("Mise à jour de %s comptes de gestionnaire", len(managers))
            # note :
            # ça aurait du être quelque chose du style :
            # nb = managers.update(departments=[models.F("department")])
            # logger.info("%d objets mis à jour", nb)
            # mais ça ne fonctionne pas : la valeur maj est un tableau contenant "F(d"
            # comme si l'expression était évalué au début de son code (bug ArrayField ?)
            # De toute façon, il n'y a que 99 gestionnaires à ce jour.
            for manager in managers:
                manager.departments = [manager.department]
                manager.save(update_fields=["departments"])
            logger.info("%d objets mis à jour", len(managers))

    dependencies = [
        (
            "users",
            "0023_rename_last_notification_email_sent_user_last_service_reminder_email_sent",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                blank=True,
                help_text="Liste des numéros des départements gérés par l'utilisateur (s’il est gestionnaire). Séparés par des virgules.",
                null=True,
                size=None,
                verbose_name="Départements en gestion",
            ),
        ),
        migrations.RunPython(update_departments_array, migrations.RunPython.noop),
    ]
