# Generated by Django 4.2.10 on 2024-02-29 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_user_departments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
    ]
