# Generated by Django 4.2.12 on 2024-07-11 10:11

from django.db import migrations

from dora.structures.models import Structure
from dora.users.enums import MainActivity

"""
Cette migration change l'activité principale de tous les membres
de structures labelisés Cap-Emploi / réseau Cheops en accompagnateurs/offreurs.
"""


def update_user_main_activity(apps, schema_editor):
    for structure in Structure.objects.filter(
        national_labels__value="cap-emploi-reseau-cheops"
    ):
        # membres validés
        structure.members.update(main_activity=MainActivity.ACCOMPAGNATEUR_OFFREUR)
        # utilisateurs invités :
        # c'est dommage de ne pas avoir une relation inverse `putative_members`
        for putative_membership in structure.putative_membership.select_related(
            "user"
        ).all():
            putative_membership.user.main_activity = MainActivity.ACCOMPAGNATEUR_OFFREUR
            putative_membership.user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_user_discovery_method_other"),
    ]

    operations = [
        migrations.RunPython(
            update_user_main_activity, reverse_code=migrations.RunPython.noop
        )
    ]
