# Generated by Django 4.2.14 on 2024-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_data_migration_cap_emploi"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sub_pc",
            field=models.UUIDField(null=True, verbose_name="Identifiant ProConnect"),
        ),
    ]
