# Generated by Django 3.2.5 on 2021-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirene", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="code_commune",
            field=models.CharField(db_index=True, max_length=5),
        ),
    ]
