# Generated by Django 3.2.12 on 2022-02-24 18:45

from django.db import migrations


def clear_siren(apps, schema_editor):
    Establishment = apps.get_model("sirene", "Establishment")
    Establishment.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sirene", "0005_alter_establishment_code_cedex"),
    ]

    operations = [
        migrations.RunPython(clear_siren, clear_siren),
    ]
