# Generated by Django 3.2.12 on 2022-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirene", "0006_empty_sirene"),
    ]

    operations = [
        migrations.RenameField(
            model_name="establishment",
            old_name="code_commune",
            new_name="city_code",
        ),
        migrations.RenameField(
            model_name="establishment",
            old_name="code_postal",
            new_name="postal_code",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="code_cedex",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="complement_adresse",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="denomination",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="denomination_parent",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="diffusable",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="distribution_speciale",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="enseigne1",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="enseigne2",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="enseigne3",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="is_social",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="libelle_cedex",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="libelle_commune",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="libelle_voie",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="nic",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="numero_voie",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="repetition_index",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="sigle_parent",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="type_voie",
        ),
        migrations.AddField(
            model_name="establishment",
            name="address1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="establishment",
            name="address2",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="establishment",
            name="city",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="establishment",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Nom"),
            preserve_default=False,
        ),
    ]
