# Generated by Django 4.0.4 on 2022-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sirene", "0007_auto_20220225_1824"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="establishment",
            options={"verbose_name": "Établissement"},
        ),
        migrations.AlterField(
            model_name="establishment",
            name="full_search_text",
            field=models.TextField(help_text="Renseigner NOM + SIRET"),
        ),
    ]
