# Generated by Django 4.0.6 on 2022-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sirene", "0008_alter_establishment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="address1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="address2",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
