# Generated by Django 4.2.10 on 2024-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirene", "0009_alter_establishment_address1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="parent_name",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                verbose_name="Nom de l’unité légale",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="establishment",
            name="full_search_text",
            field=models.TextField(help_text="Renseigner NOM + NOM UNITÉ LÉGALE"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="is_siege",
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="siren",
            field=models.CharField(db_index=True, max_length=9, verbose_name="Siren"),
        ),
    ]
