# Generated by Django 4.2.7 on 2023-12-13 14:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("structures", "0063_structure_is_obsolete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Complete"), (3, "Expired")],
                        default=1,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("orphan_structures", "Orphan Structures")]
                    ),
                ),
                ("counter", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.structure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task_type"], name="notificatio_task_ty_854c21_idx"
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_d92267_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="notificatio_updated_8e4673_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(("owner_structure", None), _negated=True),
                name="check_structure",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("task_type", "owner_structure_id")},
        ),
    ]
