# Generated by Django 4.2.7 on 2024-01-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structures", "0063_structure_is_obsolete"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="check_structure",
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="notification",
            name="owner_structureputativemember",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structureputativemember",
                verbose_name="Invitation propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("orphan_structures", "Orphan Structures"),
                    ("invited_users", "Invited Users"),
                    ("generic_task", "Generic Task"),
                ],
                verbose_name="Type de tâche",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("owner_structure", None), _negated=True),
                    models.Q(("owner_user", None), _negated=True),
                    models.Q(("owner_structureputativemember", None), _negated=True),
                    _connector="OR",
                ),
                name="check_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("task_type", "owner_structure"),
                name="unique_task_for_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("task_type", "owner_user"), name="unique_task_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("task_type", "owner_structureputativemember"),
                name="unique_task_for_invitation",
            ),
        ),
    ]
