# Generated by Django 4.2.10 on 2024-02-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0063_structure_is_obsolete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_remove_notification_check_structure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="owner_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="structures.structure",
                verbose_name="Structure propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="owner_structureputativemember",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="structures.structureputativemember",
                verbose_name="Invitation propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("orphan_structures", "Orphan Structures"),
                    ("service_activation", "Service Activation"),
                    ("invited_users", "Invited Users"),
                    ("self_invited_users", "Self Invited Users"),
                    ("generic_task", "Generic Task"),
                ],
                verbose_name="Type de tâche",
            ),
        ),
    ]
