# Generated by Django 4.2.10 on 2024-03-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_owner_structure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("orphan_structures", "Orphan Structures"),
                    ("service_activation", "Service Activation"),
                    ("invited_users", "Invited Users"),
                    ("self_invited_users", "Self Invited Users"),
                    ("users_without_structure", "Users Without Structure"),
                    ("user_account_deletion", "User Account Deletion"),
                    ("generic_task", "Generic Task"),
                ],
                verbose_name="Type de tâche",
            ),
        ),
    ]
