# Generated by Django 4.2.16 on 2024-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_alter_notificationlog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("orphan_structures", "Orphan Structures"),
                    ("service_activation", "Service Activation"),
                    ("invited_users", "Invited Users"),
                    ("self_invited_users", "Self Invited Users"),
                    ("users_without_structure", "Users Without Structure"),
                    ("user_account_deletion", "User Account Deletion"),
                    ("manager_structure_moderation", "Manager Structure Moderation"),
                    ("generic_task", "Generic Task"),
                ],
                verbose_name="type de tâche",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("orphan_structures", "Orphan Structures"),
                    ("service_activation", "Service Activation"),
                    ("invited_users", "Invited Users"),
                    ("self_invited_users", "Self Invited Users"),
                    ("users_without_structure", "Users Without Structure"),
                    ("user_account_deletion", "User Account Deletion"),
                    ("manager_structure_moderation", "Manager Structure Moderation"),
                    ("generic_task", "Generic Task"),
                ],
                verbose_name="type de tâche",
            ),
        ),
    ]
