# Generated by Django 3.2.11 on 2022-01-25 14:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dora.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        db_index=True,
                        max_length=14,
                        validators=[dora.core.validators.validate_siret],
                        verbose_name="Siret",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=140, verbose_name="Nom de l’offre"),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("contents", models.JSONField(default=dict)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
