# Generated by Django 3.2.12 on 2022-03-08 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_suggestions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicesuggestion",
            options={
                "verbose_name": "Contribution de service",
                "verbose_name_plural": "Contributions de service",
            },
        ),
    ]
