# Generated by Django 4.0.6 on 2022-08-03 08:41

from django.db import migrations

SUBSTITUTIONS = {
    "numerique--prendre-en-main-un-ordinateur": "numerique--utiliser-le-numerique-au-quotidien",
    "numerique--etre-accompagne-dans-les-demarches-administratives": "numerique--realiser-des-demarches-administratives-avec-un-accompagnement",
    "numerique--gagner-en-autonomie-dans-les-demarches-administratives": "numerique--devenir-autonome-dans-les-demarches-administratives",
}


def migrate_subcats(apps, schema_editor):
    ServiceSuggestion = apps.get_model("service_suggestions", "ServiceSuggestion")
    for s in ServiceSuggestion.objects.all():
        subcats = list(s.contents["subcategories"])

        subcats = list(set(SUBSTITUTIONS.get(value, value) for value in subcats))

        s.contents["subcategories"] = subcats
        s.save(update_fields=["contents"])


class Migration(migrations.Migration):
    dependencies = [("service_suggestions", "0068_chg_cats_suggestions")]

    operations = [
        migrations.RunPython(migrate_subcats, reverse_code=migrations.RunPython.noop),
    ]
