# Generated by Django 3.2.5 on 2021-09-06 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("department", models.CharField(db_index=True, max_length=3)),
                ("region", models.CharField(db_index=True, max_length=2)),
                ("siren_epci", models.CharField(db_index=True, max_length=20)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
