# Generated by Django 3.2.5 on 2021-09-06 16:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_express", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, srid=4326
            ),
        ),
    ]
