# Generated by Django 3.2.11 on 2022-02-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_express", "0002_alter_city_geom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="siren_epci",
            new_name="epci",
        ),
    ]
