# Generated by Django 3.2.11 on 2022-02-07 11:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_express", "0004_add_tr_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=230)),
                ("normalized_name", models.CharField(max_length=230)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
                ("region", models.CharField(db_index=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="EPCI",
            fields=[
                (
                    "code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=230)),
                ("normalized_name", models.CharField(max_length=230)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
                ("nature", models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "code",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=230)),
                ("normalized_name", models.CharField(max_length=230)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="normalized_name",
            field=models.CharField(default="", max_length=230),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="population",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="code",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=230),
        ),
        migrations.AddIndex(
            model_name="city",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="city_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="region_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddIndex(
            model_name="epci",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="epci_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"],
                name="department_name_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
    ]
