# Generated by Django 4.0.3 on 2022-05-10 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_express", "0006_auto_20220406_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="epcis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=9, primary_key=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="epci",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=9, primary_key=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="epci",
            name="regions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=9, primary_key=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
