# Generated by Django 3.2.5 on 2021-08-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0008_auto_20210813_1726"),
        ("services", "0003_auto_20210816_1953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
                verbose_name="",
            ),
        ),
    ]
