# Generated by Django 3.2.5 on 2021-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_service_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="online_forms",
        ),
        migrations.AddField(
            model_name="service",
            name="online_form",
            field=models.CharField(
                blank=True,
                max_length=280,
                verbose_name="Formulaire en ligne à compléter",
            ),
        ),
    ]
