# Generated by Django 3.2.5 on 2021-08-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0009_alter_structure_email"),
        ("services", "0008_auto_20210821_0936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_time_limited",
        ),
        migrations.AlterField(
            model_name="service",
            name="online_form",
            field=models.URLField(
                blank=True, verbose_name="Formulaire en ligne à compléter"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
                verbose_name="Structure",
            ),
        ),
    ]
