# Generated by Django 3.2.5 on 2021-08-26 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0012_alter_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="coach_orientation_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("PH", "Téléphoner"),
                        ("EM", "Envoyer un mail"),
                        ("FO", "Envoyer le formulaire d’adhésion"),
                        ("EP", "Envoyer un mail avec une fiche de prescription"),
                        ("OT", "Autre (préciser)"),
                    ],
                    max_length=2,
                ),
                size=None,
                verbose_name="Comment orienter un bénéficiaire en tant qu’accompagnateur",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="subcategories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("MO-MO", "Quand on veut se déplacer"),
                        ("MO-WK", "Quand on reprend un emploi ou une formation"),
                        ("MO-LI", "Quand on veut passer son permis"),
                        ("MO-VE", "Quand on a son permis mais pas de véhicule"),
                        ("MO-MA", "Quand on doit entretenir son véhicule"),
                        ("HO-SH", "Hebergement de courte durée"),
                        ("HO-AC", "Accéder au logement"),
                        ("HO-KE", "Conserver son logement"),
                        ("CC-IN", "Information et accompagnement des parents"),
                        ("CC-TM", "Garde ponctuelle"),
                        ("CC-LG", "Garde pérenne"),
                        ("CC-EX", "Garde périscolaire"),
                    ],
                    max_length=6,
                ),
                size=None,
                verbose_name="Sous-catégorie",
            ),
        ),
    ]
