# Generated by Django 3.2.5 on 2021-08-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_alter_service_fee_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesscondition",
            options={
                "verbose_name": "Critère d’admission",
                "verbose_name_plural": "Critères d’admission",
            },
        ),
        migrations.AlterModelOptions(
            name="concernedpublic",
            options={
                "verbose_name": "Public concerné",
                "verbose_name_plural": "Publics concernés",
            },
        ),
        migrations.AlterModelOptions(
            name="credential",
            options={
                "verbose_name": "Justificatif à fournir",
                "verbose_name_plural": "Justificatifs à fournir",
            },
        ),
        migrations.AlterModelOptions(
            name="requirement",
            options={
                "verbose_name": "Pré-requis ou compétence",
                "verbose_name_plural": "Pré-requis ou compétences",
            },
        ),
    ]
