# Generated by Django 3.2.5 on 2021-09-06 14:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_auto_20210826_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
