# Generated by Django 3.2.5 on 2021-09-06 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_auto_20210906_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
