# Generated by Django 3.2.5 on 2021-09-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0015_auto_20210920_1545"),
        ("services", "0021_alter_service_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="structures.structure",
                verbose_name="Structure",
            ),
        ),
    ]
