# Generated by Django 3.2.5 on 2021-09-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0016_auto_20210929_1542"),
        ("services", "0022_alter_service_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscondition",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="concernedpublic",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesscondition",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"),
                name="services_unique_accesscondition_by_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="concernedpublic",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"),
                name="services_unique_concernedpublic_by_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"),
                name="services_unique_credential_by_structure",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("name", "structure"),
                name="services_unique_requirement_by_structure",
            ),
        ),
    ]
