# Generated by Django 3.2.8 on 2021-10-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0023_auto_20210929_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
