# Generated by Django 3.2.8 on 2021-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_alter_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
