# Generated by Django 3.2.8 on 2021-10-25 15:56

from django.db import migrations
from django.utils import timezone


def init_pub_date(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    now = timezone.now()
    qs = Service.objects.filter(publication_date__isnull=True, is_draft=False)
    qs.update(publication_date=now)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0025_service_publication_date"),
    ]

    operations = [
        migrations.RunPython(init_pub_date),
    ]
