# Generated by Django 3.2.8 on 2021-11-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_servicemodificationhistoryitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicemodificationhistoryitem",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_common_law",
        ),
        migrations.RemoveField(
            model_name="service",
            name="recurrence",
        ),
        migrations.RemoveField(
            model_name="service",
            name="suspension_count",
        ),
    ]
