# Generated by Django 3.2.8 on 2021-11-23 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0028_auto_20211123_1919"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="recurrence_other",
            new_name="recurrence",
        ),
    ]
