# Generated by Django 3.2.8 on 2021-11-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0029_rename_recurrence_other_service_recurrence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="service",
            name="start_date",
        ),
    ]
