# Generated by Django 3.2.10 on 2021-12-15 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0032_auto_20211213_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="kinds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("SU", "Accompagnement"),
                        ("RE", "Accueil"),
                        ("FI", "Aide financière"),
                        ("MA", "Aide materielle"),
                        ("WK", "Atelier"),
                        ("FO", "Formation"),
                        ("IN", "Information"),
                    ],
                    max_length=2,
                ),
                blank=True,
                db_index=True,
                default=list,
                size=None,
                verbose_name="Type de service",
            ),
        ),
    ]
