# Generated by Django 3.2.12 on 2022-02-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0035_service_is_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="diffusion_zone_details",
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AddField(
            model_name="service",
            name="diffusion_zone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("city", "Commune"),
                    ("epci", "EPCI"),
                    ("department", "Département"),
                    ("region", "Région"),
                    ("country", "France entière"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="Zone de diffusion",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="qpv_or_zrr",
            field=models.BooleanField(default=False),
        ),
    ]
