# Generated by Django 3.2.12 on 2022-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0037_initial_diffusion_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="diffusion_zone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("city", "Commune"),
                    ("epci", "Intercommunalité (EPCI)"),
                    ("department", "Département"),
                    ("region", "Région"),
                    ("country", "France entière"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="Zone de diffusion",
            ),
        ),
    ]
