# Generated by Django 3.2.12 on 2022-03-01 15:40


from django.db import migrations


def migrate(cat, subcats):
    has_migration = False
    new_cat = cat
    new_subcats = []

    if cat == "CC":
        new_cat = "FA"
        has_migration = True

    for subcat in subcats:
        if subcat in ("CC-LG", "CC-EX", "CC-TM"):
            new_subcats.append("FA_CHILD")
            has_migration = True
        elif subcat == "CC-IN":
            new_subcats.append("FA_PARENT")
            has_migration = True
        elif subcat == "IL-AD":
            has_migration = True
        elif subcat == "IL-CO":
            new_subcats.append("IL_AUTONOMY")
            has_migration = True
        elif subcat in ("IL-FO", "IL-IN"):
            new_subcats.append("IL_JOB")
            has_migration = True
        else:
            new_subcats.append(subcat)

    return has_migration, new_cat, new_subcats


def migrate_categories(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    for service in Service.objects.all():
        has_migration, new_cat, new_subcats = migrate(
            service.category, service.subcategories
        )
        if has_migration:
            # Évite de mettre à jour les timestamps
            Service.objects.filter(pk=service.pk).update(
                category=new_cat, subcategories=new_subcats
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0040_auto_20220301_1640"),
    ]

    operations = [
        migrations.RunPython(migrate_categories, noop),
    ]
