# Generated by Django 3.2.12 on 2022-03-01 19:12

from django.db import migrations


def remove_dups(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    for service in Service.objects.all():
        Service.objects.filter(pk=service.pk).update(
            subcategories=list(set(service.subcategories))
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0042_auto_20220301_1945"),
    ]

    operations = [
        migrations.RunPython(remove_dups, noop),
    ]
