# Generated by Django 3.2.12 on 2022-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0043_removedup_subcats"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryAccessMode2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoachOrientationMode2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationKind2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceCategories2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceKind2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceSubCategories2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="service",
            name="beneficiaries_access_modes2",
            field=models.ManyToManyField(
                blank=True,
                to="services.BeneficiaryAccessMode2",
                verbose_name="Comment mobiliser la solution en tant que bénéficiaire",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="categories2",
            field=models.ManyToManyField(
                blank=True,
                to="services.ServiceCategories2",
                verbose_name="Catégories principales",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="coach_orientation_modes2",
            field=models.ManyToManyField(
                blank=True,
                to="services.CoachOrientationMode2",
                verbose_name="Comment orienter un bénéficiaire en tant qu’accompagnateur",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="kinds2",
            field=models.ManyToManyField(
                blank=True, to="services.ServiceKind2", verbose_name="Type de service"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="location_kinds2",
            field=models.ManyToManyField(
                blank=True,
                to="services.LocationKind2",
                verbose_name="Lieu de déroulement",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="subcategories2",
            field=models.ManyToManyField(
                blank=True,
                to="services.ServiceSubCategories2",
                verbose_name="Sous-catégorie",
            ),
        ),
    ]
