# Generated by Django 3.2.12 on 2022-03-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0046_auto_20220308_1754"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiaryaccessmode",
            options={
                "verbose_name": "Mode d'orientation bénéficiaire",
                "verbose_name_plural": "Modes d'orientation bénéficiaire",
            },
        ),
        migrations.AlterModelOptions(
            name="coachorientationmode",
            options={
                "verbose_name": "Mode d'orientation accompagnateur",
                "verbose_name_plural": "Modes d'orientation accompagnateur",
            },
        ),
        migrations.AlterModelOptions(
            name="locationkind",
            options={
                "verbose_name": "Lieu de déroulement",
                "verbose_name_plural": "Lieux de déroulement",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "verbose_name": "Catégorie principale",
                "verbose_name_plural": "Catégories principales",
            },
        ),
        migrations.AlterModelOptions(
            name="servicekind",
            options={
                "verbose_name": "Type de service",
                "verbose_name_plural": "Types de service",
            },
        ),
        migrations.AlterModelOptions(
            name="servicesubcategory",
            options={"verbose_name": "Sous-catégorie"},
        ),
    ]
