# Generated by Django 3.2.12 on 2022-03-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0047_auto_20220308_1815"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicemodificationhistoryitem",
            options={
                "ordering": ["-date"],
                "verbose_name": "Historique de modification de service",
            },
        ),
    ]
