# Generated by Django 3.2.12 on 2022-03-16 09:03

from django.db import migrations


def rename_value(Model, old_value, new_value):
    Model.objects.filter(value=old_value).update(value=new_value)


def rename_enums(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    rename_value(ServiceCategory, "CR", "creation-activite")
    rename_value(ServiceCategory, "DI", "numerique")
    rename_value(ServiceCategory, "EQ", "equipement-alimentation")
    rename_value(ServiceCategory, "FA", "famille")
    rename_value(ServiceCategory, "FI", "difficultes-financieres")
    rename_value(ServiceCategory, "FL", "apprendre-francais")
    rename_value(ServiceCategory, "GL", "acc-global-indiv")
    rename_value(ServiceCategory, "HA", "handicap")
    rename_value(ServiceCategory, "HE", "sante")
    rename_value(ServiceCategory, "HO", "logement-hebergement")
    rename_value(ServiceCategory, "IL", "illettrisme")
    rename_value(ServiceCategory, "JO", "emploi")
    rename_value(ServiceCategory, "MO", "mobilite")
    rename_value(ServiceCategory, "RE", "remobilisation")
    rename_value(ServiceCategory, "RI", "acces-aux-droits")

    #
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")
    rename_value(ServiceSubCategory, "CR-EL", "creation-activite--elaborer-projet")
    rename_value(ServiceSubCategory, "CR-ID", "creation-activite--de-lidee-au-projet")
    rename_value(ServiceSubCategory, "CR-ST", "creation-activite--demarrer-activite")
    rename_value(ServiceSubCategory, "DI-AD", "numerique--realiser-demarche-en-ligne")
    rename_value(
        ServiceSubCategory,
        "DI-BA",
        "numerique--prendre-en-main-equipement-informatique",
    )
    rename_value(ServiceSubCategory, "DI-CH", "numerique--accompagner-enfant")
    rename_value(
        ServiceSubCategory, "DI-CN", "numerique--creer-gerer-contenus-numeriques"
    )
    rename_value(ServiceSubCategory, "DI-CO", "numerique--echanger-avec-proches")
    rename_value(ServiceSubCategory, "DI-EM", "numerique--usage-courriels")
    rename_value(ServiceSubCategory, "DI-JO", "numerique--trouver-emploi-formation")
    rename_value(ServiceSubCategory, "DI-NA", "numerique--naviguer-internet")
    rename_value(ServiceSubCategory, "DI-PH", "numerique--utiliser-smartphone")
    rename_value(ServiceSubCategory, "DI-WD", "numerique--connaitre-env-numerique")
    rename_value(ServiceSubCategory, "DI-WP", "numerique--bases-traitement-texte")
    rename_value(
        ServiceSubCategory, "EQ_APPLIANCE", "equipement-alimentation--electromenager"
    )
    rename_value(ServiceSubCategory, "EQ_CLOTH", "equipement-alimentation--habillement")
    rename_value(
        ServiceSubCategory,
        "EQ_COMP",
        "equipement-alimentation--acces-materiel-informatique",
    )
    rename_value(ServiceSubCategory, "EQ_FOOD", "equipement-alimentation--alimentation")
    rename_value(
        ServiceSubCategory, "EQ_PHONE", "equipement-alimentation--acces-telephone"
    )
    rename_value(ServiceSubCategory, "FA_CHILD", "famille--garde-enfants")
    rename_value(ServiceSubCategory, "FA_NOFAM", "famille--jeune-sans-soutien-familial")
    rename_value(ServiceSubCategory, "FA_PARENT", "famille--accompagnement-parents")
    rename_value(ServiceSubCategory, "FA_SUPPORT", "famille--soutien-familles")
    rename_value(
        ServiceSubCategory, "FA_VIOLENCE", "famille--violences-intrafamiliales"
    )
    rename_value(
        ServiceSubCategory,
        "FI_ACCOUNT",
        "difficultes-financieres--utilisation-compte-bancaire",
    )
    rename_value(
        ServiceSubCategory, "FI_BUDGET", "difficultes-financieres--gerer-budget"
    )
    rename_value(
        ServiceSubCategory,
        "FI_DEBT",
        "difficultes-financieres--prevention-surendettement",
    )
    rename_value(
        ServiceSubCategory,
        "FI_HELP",
        "difficultes-financieres--accompagnement-difficultes-financieres",
    )
    rename_value(
        ServiceSubCategory,
        "FL-CO",
        "apprendre-francais--communiquer-vie-tous-les-jours",
    )
    rename_value(ServiceSubCategory, "FL-FO", "apprendre-francais--suivre-formation")
    rename_value(
        ServiceSubCategory, "FL-IN", "apprendre-francais--accompagnement-insertion-pro"
    )
    rename_value(
        ServiceSubCategory, "HA_ACC", "handicap--accompagnement-structure-specialisee"
    )
    rename_value(ServiceSubCategory, "HA_DESK", "handicap--adaptation-poste-travail")
    rename_value(ServiceSubCategory, "HA_HOUSING", "handicap--adapter-logement")
    rename_value(ServiceSubCategory, "HA_RECOG", "handicap--faire-reconnaitre-handicap")
    rename_value(
        ServiceSubCategory, "HA_RIGHTS", "handicap--connaissance-droits-travailleurs"
    )
    rename_value(ServiceSubCategory, "HA_WORK", "handicap--retour-maintien-emploi")
    rename_value(ServiceSubCategory, "HE_ADDICT", "sante--addiction")
    rename_value(ServiceSubCategory, "HE_CURE", "sante--soin-prevention-maladie")
    rename_value(
        ServiceSubCategory, "HE_EXPENSE", "sante--prise-en-charge-frais-medicaux"
    )
    rename_value(ServiceSubCategory, "HE_PSY", "sante--bien-etre-psy")
    rename_value(ServiceSubCategory, "HO_AD", "logement-hebergement--adapter-logement")
    rename_value(ServiceSubCategory, "HO_MO", "logement-hebergement--demenagement")
    rename_value(
        ServiceSubCategory, "HO_WK", "logement-hebergement--reprendre-emploi-formation"
    )
    rename_value(
        ServiceSubCategory, "HO-AC", "logement-hebergement--acommpagnement-logement"
    )
    rename_value(ServiceSubCategory, "HO-KE", "logement-hebergement--probleme-logement")
    rename_value(
        ServiceSubCategory, "HO-SH", "logement-hebergement--mal-loge-sans-logis"
    )
    rename_value(ServiceSubCategory, "IL_AUTONOMY", "illettrisme--etre-autonome")
    rename_value(
        ServiceSubCategory, "IL_CLEA", "illettrisme--valider-certification-clea"
    )
    rename_value(
        ServiceSubCategory, "IL_DEFECT", "illettrisme--surmonter-trouble-apprentissage"
    )
    rename_value(
        ServiceSubCategory, "IL_DETECT", "illettrisme--reperer-situation-illettrisme"
    )
    rename_value(ServiceSubCategory, "IL_DIGITAL", "illettrisme--utiliser-numerique")
    rename_value(ServiceSubCategory, "IL_DRIVING", "illettrisme--permis-conduire")
    rename_value(
        ServiceSubCategory, "IL_INFO", "illettrisme--info-acquisition-connaissances"
    )
    rename_value(ServiceSubCategory, "IL_JOB", "illettrisme--trouver-emploi-formation")
    rename_value(ServiceSubCategory, "IL_SCHOOL", "illettrisme--accompagner-scolarite")
    rename_value(ServiceSubCategory, "IL_VOCAB", "illettrisme--ameliorer-vocabulaire")
    rename_value(ServiceSubCategory, "JO_CHOOSE", "emploi--choisir-metier")
    rename_value(ServiceSubCategory, "JO_FIND", "emploi--trouver-emploi")
    rename_value(ServiceSubCategory, "JO_PREPARE", "emploi--preparer-candidature")
    rename_value(ServiceSubCategory, "MO_2W", "mobilite--utiliser-deux-roues")
    rename_value(ServiceSubCategory, "MO_BLK", "mobilite--identifier-freins")
    rename_value(
        ServiceSubCategory, "MO_HLP", "mobilite--accompagnement-parcours-mobilite"
    )
    rename_value(ServiceSubCategory, "MO-LI", "mobilite--preparer-permis")
    rename_value(ServiceSubCategory, "MO-MA", "mobilite--entretenir-vehicule")
    rename_value(
        ServiceSubCategory, "MO-MO", "mobilite--se-deplacer-sans-permis-ou-vehicule"
    )
    rename_value(ServiceSubCategory, "MO-VE", "mobilite--louer-acheter-vehicule")
    rename_value(ServiceSubCategory, "MO-WK", "mobilite--reprendre-emploi-formation")
    rename_value(
        ServiceSubCategory, "RE_EVAL", "remobilisation--identifier-competences"
    )
    rename_value(ServiceSubCategory, "RE_SOCIAL", "remobilisation--lien-social")
    rename_value(ServiceSubCategory, "RE_TRUST", "remobilisation--restaurer-confiance")
    rename_value(ServiceSubCategory, "RE_WELLBEING", "remobilisation--bien-etre")
    rename_value(
        ServiceSubCategory,
        "RI_ADM_ACC",
        "acces-aux-droits--accompagnement-demarches-admin",
    )
    rename_value(
        ServiceSubCategory,
        "RI_ASYLUM",
        "acces-aux-droits--demandeurs-asile-naturalisation",
    )
    rename_value(
        ServiceSubCategory, "RI_JUD_ACC", "acces-aux-droits--accompagnement-juridique"
    )
    rename_value(ServiceSubCategory, "RI_KNOW", "acces-aux-droits--connaitre-droits")

    #
    ServiceKind = apps.get_model("services", "ServiceKind")
    rename_value(ServiceKind, "SU", "accompagnement")
    rename_value(ServiceKind, "RE", "accueil")
    rename_value(ServiceKind, "FI", "aide-financiere")
    rename_value(ServiceKind, "MA", "aide-materielle")
    rename_value(ServiceKind, "WK", "atelier")
    rename_value(ServiceKind, "FO", "formation")
    rename_value(ServiceKind, "IN", "information")

    #
    BeneficiaryAccessMode = apps.get_model("services", "BeneficiaryAccessMode")
    rename_value(BeneficiaryAccessMode, "OT", "autre")
    rename_value(BeneficiaryAccessMode, "EM", "envoyer-courriel")
    rename_value(BeneficiaryAccessMode, "OS", "se-presenter")
    rename_value(BeneficiaryAccessMode, "PH", "telephoner")

    #
    CoachOrientationMode = apps.get_model("services", "CoachOrientationMode")
    rename_value(CoachOrientationMode, "OT", "autre")
    rename_value(CoachOrientationMode, "FO", "envoyer-formulaire")
    rename_value(CoachOrientationMode, "EM", "envoyer-courriel")
    rename_value(CoachOrientationMode, "EP", "envoyer-fiche-prescription")
    rename_value(CoachOrientationMode, "PH", "telephoner")

    #
    LocationKind = apps.get_model("services", "LocationKind")
    rename_value(LocationKind, "RE", "a-distance")
    rename_value(LocationKind, "OS", "en-presentiel")


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0048_alter_servicemodificationhistoryitem_options"),
    ]

    operations = [
        migrations.RunPython(rename_enums, reverse_code=migrations.RunPython.noop),
    ]
