# Generated by Django 4.0.3 on 2022-04-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0049_rename_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_model",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="services.service",
            ),
        ),
    ]
