# Generated by Django 4.0.3 on 2022-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0050_service_is_model_service_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="last_sync_checksum",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="service",
            name="sync_checksum",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="service",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ville"),
        ),
    ]
