# Generated by Django 4.0.3 on 2022-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0050_service_is_model_service_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="common_fields_checksum",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
