# Generated by Django 4.0.3 on 2022-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0051_service_common_fields_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ville"),
        ),
    ]
