# Generated by Django 4.0.4 on 2022-06-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0052_add_other_subcats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodificationhistoryitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_item",
                to="services.service",
            ),
        ),
    ]
