# Generated by Django 4.0.4 on 2022-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0053_alter_servicemodificationhistoryitem_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUGGESTION", "Suggestion"),
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("UNPUBLISHED", "Unpublished"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
