# Generated by Django 4.0.4 on 2022-06-27 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0055_migrate_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceModel",
            fields=[],
            options={
                "verbose_name": "Modèle",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("services.service",),
        ),
        migrations.AlterField(
            model_name="service",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="services.servicemodel",
            ),
        ),
    ]
