# Generated by Django 4.0.6 on 2022-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0057_service_filling_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="filling_duration",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
