# Generated by Django 4.0.6 on 2022-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0058_alter_service_filling_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="last_draft_notification_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
