# Generated by Django 4.0.4 on 2022-06-27 22:02

from cProfile import label
from django.db import migrations

from dora.services.migration_utils import (
    create_subcategory,
    delete_subcategory,
    replace_subcategory,
    update_subcategory_value_and_label,
)

"""
-- Avant: 15 => Après : 15
SELECT COUNT(*) from services_servicecategory;

-- Avant : 12 (11+autre) => Après: 15 (14+1 autre)
SELECT COUNT(*) FROM services_servicesubcategory WHERE "value" LIKE 'numerique--%';

SELECT * FROM services_servicesubcategory WHERE "value" LIKE 'numerique--%';

-- Plus de catégories accompagner-enfant
SELECT * FROM services_servicesubcategory WHERE "value" LIKE 'numerique--%';


-- Avant 0 => après 1
SELECT COUNT(*) FROM services_servicesubcategory WHERE "value" LIKE 'numerique--utiliser-le-numerique-au-quotidien';


-- Avant 93 => Après 0
SELECT DISTINCT(service_id) FROM services_service_subcategories WHERE servicesubcategory_id IN (
SELECT id FROM services_servicesubcategory WHERE "value" IN ('numerique--creer-gerer-contenus-numeriques', 'numerique--echanger-avec-proches', 'numerique--naviguer-internet', 'numerique--usage-courriels')
);

-- Avant 0 => après 93
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'numerique--utiliser-le-numerique-au-quotidien');


-- Avant 1 => après 0
SELECT COUNT(*) FROM services_servicesubcategory WHERE "value" LIKE 'numerique--accompagner-enfant';

-- Avant 17 => après 0
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'numerique--accompagner-enfant');


-- 1 service a à la fois `numerique--autre` et `numerique--accompagner-enfant`
SELECT service_id, COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id IN (SELECT id FROM services_servicesubcategory WHERE "value" = 'numerique--accompagner-enfant' OR  "value" = 'numerique--autre') GROUP BY service_id ORDER BY count DESC;

-- Avant 16 => Après 16 + 17 - 1= 32
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'numerique--autre');


-- Avant 0 => Après 4
SELECT * FROM services_servicesubcategory WHERE "value" IN ('numerique--etre-accompagne-dans-les-demarches-administratives','numerique--acceder-a-une-connexion-internet','numerique--acceder-a-du-materiel','numerique--creer-et-developper-mon-entreprise');
"""


def migrate_services_options(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    # 2 - Numérique
    """
    1:
        - remplacer les références à "numerique--accompagner-enfant" vers "numerique--autre"
        - supprimer "numerique--accompagner-enfant"
    """
    numerique_value = "numerique"

    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value=f"{numerique_value}--accompagner-enfant",
        to_value=f"{numerique_value}--autre",
    )
    delete_subcategory(ServiceSubCategory, f"{numerique_value}--accompagner-enfant")

    """
    2:
        - Ajouter besoins :
            - "numerique--etre-accompagne-dans-les-demarches-administratives" => "Être accompagné dans les démarches administratives"
            - "numerique--acceder-a-une-connexion-internet" => "Accéder à une connexion internet"
            - "numerique--acceder-a-du-materiel" => "Accéder à du matériel"
            - "numerique--creer-et-developper-mon-entreprise" => "Créer et développer mon entreprise"
    """
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--etre-accompagne-dans-les-demarches-administratives",
        label="Être accompagné dans les démarches administratives",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--acceder-a-une-connexion-internet",
        label="Accéder à une connexion internet",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--acceder-a-du-materiel",
        label="Accéder à du matériel",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--creer-et-developper-mon-entreprise",
        label="Créer et développer mon entreprise",
    )

    """
    3:
        - Changer value et label :
            - "numerique--connaitre-env-numerique" => "numerique--approfondir-ma-culture-numerique" & "Approfondir ma culture numérique"
            - "numerique--prendre-en-main-equipement-informatique" => "numerique--prendre-en-main-un-ordinateur" & "Prendre en main un ordinateur"`
            - "numerique--realiser-demarche-en-ligne" => "numerique--gagner-en-autonomie-dans-les-demarches-administratives" & "Gagner en autonomie dans les démarches administratives"
            - "numerique--trouver-emploi-formation" => "numerique--favoriser-mon-insertion-professionnelle" & "Favoriser mon insertion professionnelle"
            - "numerique--utiliser-smartphone" => "numerique--prendre-en-main-un-smartphone-ou-une-tablette" & "Prendre en main un smartphone ou une tablette"
    """

    update_subcategory_value_and_label(
        ServiceSubCategory,
        old_value=f"{numerique_value}--connaitre-env-numerique",
        new_value=f"{numerique_value}--approfondir-ma-culture-numerique",
        new_label="Approfondir ma culture numérique",
    )
    update_subcategory_value_and_label(
        ServiceSubCategory,
        old_value=f"{numerique_value}--prendre-en-main-equipement-informatique",
        new_value=f"{numerique_value}--prendre-en-main-un-ordinateur",
        new_label="Prendre en main un ordinateur",
    )
    update_subcategory_value_and_label(
        ServiceSubCategory,
        old_value=f"{numerique_value}--realiser-demarche-en-ligne",
        new_value=f"{numerique_value}--gagner-en-autonomie-dans-les-demarches-administratives",
        new_label="Gagner en autonomie dans les démarches administratives",
    )
    update_subcategory_value_and_label(
        ServiceSubCategory,
        old_value=f"{numerique_value}--trouver-emploi-formation",
        new_value=f"{numerique_value}--favoriser-mon-insertion-professionnelle",
        new_label="Favoriser mon insertion professionnelle",
    )

    update_subcategory_value_and_label(
        ServiceSubCategory,
        old_value=f"{numerique_value}--utiliser-smartphone",
        new_value=f"{numerique_value}--prendre-en-main-un-smartphone-ou-une-tablette",
        new_label="Prendre en main un smartphone ou une tablette",
    )

    """
    4:
        - Modifier besoins :
            - Creer "numerique--utiliser-le-numerique-au-quotidien" avec label "Utiliser le numérique au quotidien"
            - Migrer "numerique--creer-gerer-contenus-numeriques", "numerique--echanger-avec-proches", "numerique--naviguer-internet", "numerique--usage-courriels" vers "numerique--utiliser-le-numerique-au-quotidien","numerique--bases-traitement-texte"
            - Supprimer "numerique--creer-gerer-contenus-numeriques", "numerique--echanger-avec-proches", "numerique--naviguer-internet", "numerique--usage-courriels"
    """

    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--utiliser-le-numerique-au-quotidien",
        label="Utiliser le numérique au quotidien",
    )
    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value=f"{numerique_value}--creer-gerer-contenus-numeriques",
        to_value=f"{numerique_value}--utiliser-le-numerique-au-quotidien",
    )
    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value=f"{numerique_value}--echanger-avec-proches",
        to_value=f"{numerique_value}--utiliser-le-numerique-au-quotidien",
    )
    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value=f"{numerique_value}--naviguer-internet",
        to_value=f"{numerique_value}--utiliser-le-numerique-au-quotidien",
    )
    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value=f"{numerique_value}--usage-courriels",
        to_value=f"{numerique_value}--utiliser-le-numerique-au-quotidien",
    )
    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value=f"{numerique_value}--bases-traitement-texte",
        to_value=f"{numerique_value}--utiliser-le-numerique-au-quotidien",
    )
    delete_subcategory(
        ServiceSubCategory, f"{numerique_value}--creer-gerer-contenus-numeriques"
    )
    delete_subcategory(ServiceSubCategory, f"{numerique_value}--echanger-avec-proches")
    delete_subcategory(ServiceSubCategory, f"{numerique_value}--naviguer-internet")
    delete_subcategory(ServiceSubCategory, f"{numerique_value}--usage-courriels")
    delete_subcategory(ServiceSubCategory, f"{numerique_value}--bases-traitement-texte")


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0061_servicemodel_alter_service_creation_activite"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_options, reverse_code=migrations.RunPython.noop
        ),
    ]
