# Generated by Django 4.0.4 on 2022-06-27 22:02

from django.db import migrations

from dora.services.migration_utils import (
    create_subcategory,
    delete_subcategory,
    replace_subcategory,
)

"""
-- Avant: 15 => Après : 15
SELECT COUNT(*) from services_servicecategory;

-- Avant : 12 (11+autre) => Après: 15 (14+1 autre)
SELECT COUNT(*) FROM services_servicesubcategory WHERE "value" LIKE 'numerique--%';

-- Plus de catégories accompagner-enfant
SELECT * FROM services_servicesubcategory WHERE "value" LIKE 'numerique--%';

-- Avant 1 => après 0
SELECT COUNT(*) FROM services_servicesubcategory WHERE "value" LIKE 'numerique--accompagner-enfant';



-- Avant 17 => après 0
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'numerique--accompagner-enfant');


-- 1 service a à la fois `numerique--autre` et `numerique--accompagner-enfant`
SELECT service_id, COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id IN (SELECT id FROM services_servicesubcategory WHERE "value" = 'numerique--accompagner-enfant' OR  "value" = 'numerique--autre') GROUP BY service_id ORDER BY count DESC;

-- Avant 16 => Après 16 + 17 - 1= 32
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'numerique--autre');


-- Avant 0 => Après 4
SELECT * FROM services_servicesubcategory WHERE "value" IN ('numerique--etre-accompagne-dans-les-demarches-administratives','numerique--acceder-a-une-connexion-internet','numerique--acceder-a-du-materiel','numerique--creer-et-developper-mon-entreprise');
"""


def migrate_services_options(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    # 2 - Numérique
    """
    1:
        - remplacer les références à "numerique--accompagner-enfant" vers "numerique--autre"
        - supprimer "numerique--accompagner-enfant"
    """
    numerique_slug = "numerique"

    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_slug=f"{numerique_slug}--accompagner-enfant",
        to_slug=f"{numerique_slug}--autre",
    )
    delete_subcategory(ServiceSubCategory, f"{numerique_slug}--accompagner-enfant")

    """
    2:
        - Ajouter besoins :
            - "numerique--acceder-a-une-connexion-internet" => "Accéder à une connexion internet"
            - "numerique--acceder-a-du-materiel" => "Accéder à du matériel"
            - "numerique--creer-et-developper-mon-entreprise" => "Créer et développer mon entreprise"
    """
    create_subcategory(
        ServiceSubCategory,
        slug=f"{numerique_slug}--etre-accompagne-dans-les-demarches-administratives",
        label="Être accompagné dans les démarches administratives",
    )
    create_subcategory(
        ServiceSubCategory,
        slug=f"{numerique_slug}--acceder-a-une-connexion-internet",
        label="Accéder à une connexion internet",
    )
    create_subcategory(
        ServiceSubCategory,
        slug=f"{numerique_slug}--acceder-a-du-materiel",
        label="Accéder à du matériel",
    )
    create_subcategory(
        ServiceSubCategory,
        slug=f"{numerique_slug}--creer-et-developper-mon-entreprise",
        label="Créer et développer mon entreprise",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0061_servicemodel_alter_service_creation_activite"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_options, reverse_code=migrations.RunPython.noop
        ),
    ]
