# Generated by Django 4.0.4 on 2022-06-27 22:02

from django.db import migrations

from dora.services.migration_utils import (
    add_categories_and_subcategories_if_subcategory,
    create_category,
    create_subcategory,
    delete_category,
    delete_subcategory,
    unlink_services_from_category,
    unlink_services_from_subcategory,
)

"""
-- Avant 1 => après 0
SELECT * FROM services_servicecategory WHERE "value" = 'emploi';

-- Avant 0 => après 3
SELECT * FROM services_servicecategory WHERE "value" IN ('emploi-choisir-metier','emploi-preparer-sa-candidature','emploi-trouver-emploi');

-- Avant 4 => Après 0
SELECT * FROM services_servicesubcategory WHERE "value" LIKE 'emploi--%';

-- Avant 0 => Après 5
SELECT * FROM services_servicesubcategory WHERE "value" LIKE 'emploi-choisir-metier--%';
-- Avant 0 => Après 5
SELECT * FROM services_servicesubcategory WHERE "value" LIKE 'emploi-preparer-sa-candidature--%';
-- Avant 0 => Après 5
SELECT * FROM services_servicesubcategory WHERE "value" LIKE 'emploi-trouver-emploi--%';


-- Avant 19 => Après 0
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--autre');


-- 13 services ont en commun "emploi--preparer-candidature" et "emploi--autre"
SELECT COUNT(DISTINCT(service_id)) FROM  services_service_subcategories WHERE service_id IN (
    SELECT service_id FROM services_service_subcategories WHERE servicesubcategory_id IN (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--preparer-candidature')
) AND service_id IN (
    SELECT service_id FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--autre')
);

-- 11 services ont en commun "emploi--choisir-metier" et "emploi--autre"
SELECT COUNT(DISTINCT(service_id)) FROM  services_service_subcategories WHERE service_id IN (
    SELECT service_id FROM services_service_subcategories WHERE servicesubcategory_id IN (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--choisir-metier')
) AND service_id IN (
    SELECT service_id FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--autre')
);

-- 16 services ont en commun "emploi--preparer-candidature" et "emploi--autre"
SELECT COUNT(DISTINCT(service_id)) FROM  services_service_subcategories WHERE service_id IN (
    SELECT service_id FROM services_service_subcategories WHERE servicesubcategory_id IN (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--trouver-emploi')
) AND service_id IN (
    SELECT service_id FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--autre')
);




-- Avant 151 => Après 0
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--choisir-metier');
-- Avant 0 => Après 151 + (19-11) => 159
SELECT COUNT(*) FROM services_service_categories WHERE servicecategory_id = (SELECT id FROM services_servicecategory WHERE "value" = 'emploi-choisir-metier');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-choisir-metier--autre');
-- Avant 0 => Après 151
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-choisir-metier--identifier-ses-points-forts-et-ses-competences');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-choisir-metier--connaitre-les-opportunites-demploi');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-choisir-metier--decouvrir-un-metier-ou-un-secteur-dactivite');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-choisir-metier--confirmer-son-choix-de-metier');




-- Avant 120 => Après 0
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--preparer-candidature');
-- Avant 0 => Après 120 + (19-13) => 126
SELECT COUNT(*) FROM services_service_categories WHERE servicecategory_id = (SELECT id FROM services_servicecategory WHERE "value" = 'emploi-preparer-sa-candidature');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-preparer-sa-candidature--autre');
-- Avant 0 => Après 120
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-preparer-sa-candidature--valoriser-ses-competences');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-preparer-sa-candidature--realiser-un-cv-etou-une-lettre-de-motivation');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-preparer-sa-candidature--developper-son-reseau');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-preparer-sa-candidature--organiser-ses-demarches-de-recherche-demploi');


-- Avant 216 => Après 0
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi--trouver-emploi');
-- Avant 0 => Après 216 + (19-16) = 219
SELECT COUNT(*) FROM services_service_categories WHERE servicecategory_id = (SELECT id FROM services_servicecategory WHERE "value" = 'emploi-trouver-emploi');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-trouver-emploi--autre');
-- Avant 0 => Après 216
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-trouver-emploi--repondre-a-des-offres-demploi');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-trouver-emploi--faire-des-candidatures-spontanees');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-trouver-emploi--suivre-ses-candidatures-et-relancer-les-employeurs');
SELECT COUNT(*) FROM services_service_subcategories WHERE servicesubcategory_id = (SELECT id FROM services_servicesubcategory WHERE "value" = 'emploi-trouver-emploi--convaincre-un-recruteur-en-entretien');

"""


def migrate_services_options(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    # 3 - Pôle emploi
    """
    1- Créer
        1.1 Thématiques :
            "emploi-choisir-metier" => "Emploi - Choisir un métier"
            "emploi-preparer-sa-candidature" => "Emploi - Préparer sa candidature"
            "emploi-trouver-emploi" => "Emploi - Trouver un emploi"

        1.2 Besoins :
            "emploi-choisir-metier--identifier-ses-points-forts-et-ses-competences" => Identifier ses points forts et ses compétences
            "emploi-choisir-metier--connaitre-les-opportunites-demploi" => Connaître les opportunités d’emploi
            "emploi-choisir-metier--decouvrir-un-metier-ou-un-secteur-dactivite" => Découvrir un métier ou un secteur d’activité
            "emploi-choisir-metier--confirmer-son-choix-de-metier" => Confirmer son choix de métier
            "emploi-choisir-metier--autre" => Autre

            "emploi-preparer-sa-candidature--valoriser-ses-competences" => Valoriser ses compétences
            "emploi-preparer-sa-candidature--realiser-un-cv-etou-une-lettre-de-motivation" => Réaliser un CV et/ou une lettre de motivation
            "emploi-preparer-sa-candidature--developper-son-reseau" => Développer son réseau
            "emploi-preparer-sa-candidature--organiser-ses-demarches-de-recherche-demploi" => Organiser ses démarches de recherche d’emploi
            "emploi-preparer-sa-candidature--autre" => Autre

            "emploi-trouver-emploi--repondre-a-des-offres-demploi" => Répondre à des offres d’emploi
            "emploi-trouver-emploi--faire-des-candidatures-spontanees" => Faire des candidatures spontanées
            "emploi-trouver-emploi--suivre-ses-candidatures-et-relancer-les-employeurs" => Suivre ses candidatures et relancer les employeurs
            "emploi-trouver-emploi--convaincre-un-recruteur-en-entretien" => Convaincre un recruteur en entretien
            "emploi-trouver-emploi--autre" => Autre
    """
    emploi_choisir_un_metier_value = "emploi-choisir-metier"
    emploi_preparer_sa_candidature_value = "emploi-preparer-sa-candidature"
    emploi_trouver_un_emploi_value = "emploi-trouver-emploi"

    create_category(
        ServiceCategory,
        value=emploi_choisir_un_metier_value,
        label="Emploi - Choisir un métier",
    )
    create_category(
        ServiceCategory,
        value=emploi_preparer_sa_candidature_value,
        label="Emploi - Préparer sa candidature",
    )
    create_category(
        ServiceCategory,
        value=emploi_trouver_un_emploi_value,
        label="Emploi - Trouver un emploi",
    )

    # emploi-choisir-metier--
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_choisir_un_metier_value}--identifier-ses-points-forts-et-ses-competences",
        label="Identifier ses points forts et ses compétences",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_choisir_un_metier_value}--connaitre-les-opportunites-demploi",
        label="Connaître les opportunités d’emploi",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_choisir_un_metier_value}--decouvrir-un-metier-ou-un-secteur-dactivite",
        label="Découvrir un métier ou un secteur d’activité",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_choisir_un_metier_value}--confirmer-son-choix-de-metier",
        label="Confirmer son choix de métier",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_choisir_un_metier_value}--autre",
        label="Autre",
    )

    # emploi-preparer-sa-candidature--
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_preparer_sa_candidature_value}--valoriser-ses-competences",
        label="Valoriser ses compétences",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_preparer_sa_candidature_value}--realiser-un-cv-etou-une-lettre-de-motivation",
        label="Réaliser un CV et/ou une lettre de motivation",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_preparer_sa_candidature_value}--developper-son-reseau",
        label="Développer son réseau",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_preparer_sa_candidature_value}--organiser-ses-demarches-de-recherche-demploi",
        label="Organiser ses démarches de recherche d’emploi",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_preparer_sa_candidature_value}--autre",
        label="Autre",
    )

    # emploi-trouver-emploi--
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_trouver_un_emploi_value}--repondre-a-des-offres-demploi",
        label="Répondre à des offres d’emploi",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_trouver_un_emploi_value}--faire-des-candidatures-spontanees",
        label="Faire des candidatures spontanées",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_trouver_un_emploi_value}--suivre-ses-candidatures-et-relancer-les-employeurs",
        label="Suivre ses candidatures et relancer les employeurs",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_trouver_un_emploi_value}--convaincre-un-recruteur-en-entretien",
        label="Convaincre un recruteur en entretien",
    )
    create_subcategory(
        ServiceSubCategory,
        value=f"{emploi_trouver_un_emploi_value}--autre",
        label="Autre",
    )

    """
        2:
            Rattacher les services liés au besoin "emploi--choisir-metier" à la thématique "emploi-choisir-metier" et aux besoins : "emploi-choisir-metier--identifier-ses-points-forts-et-ses-competences" -- "emploi-choisir-metier--connaitre-les-opportunites-demploi" -- "emploi-choisir-metier--decouvrir-un-metier-ou-un-secteur-dactivite" -- "emploi-choisir-metier--confirmer-son-choix-de-metier" -- "emploi-choisir-metier--autre"
            Rattacher les services liés au besoin "emploi--preparer-candidature" à la thématique "emploi-preparer-sa-candidature" et aux besoins : "emploi-preparer-sa-candidature--valoriser-ses-competences" -- "emploi-preparer-sa-candidature--realiser-un-cv-etou-une-lettre-de-motivation" -- "emploi-preparer-sa-candidature--developper-son-reseau" -- "emploi-preparer-sa-candidature--organiser-ses-demarches-de-recherche-demploi" -- "emploi-preparer-sa-candidature--autre"
            Rattacher les services liés au besoin "emploi--trouver-emploi" à la thématique "emploi-trouver-emploi" et aux besoins : "emploi-trouver-emploi--repondre-a-des-offres-demploi" -- "emploi-trouver-emploi--faire-des-candidatures-spontanees" -- "emploi-trouver-emploi--suivre-ses-candidatures-et-relancer-les-employeurs" -- "emploi-trouver-emploi--convaincre-un-recruteur-en-entretien" -- "emploi-trouver-emploi--autre"
    """
    add_categories_and_subcategories_if_subcategory(
        ServiceCategory,
        ServiceSubCategory,
        Service,
        categories_value_to_add=[emploi_choisir_un_metier_value],
        subcategory_value_to_add=[
            f"{emploi_choisir_un_metier_value}--identifier-ses-points-forts-et-ses-competences",
            f"{emploi_choisir_un_metier_value}--connaitre-les-opportunites-demploi",
            f"{emploi_choisir_un_metier_value}--decouvrir-un-metier-ou-un-secteur-dactivite",
            f"{emploi_choisir_un_metier_value}--confirmer-son-choix-de-metier",
            f"{emploi_choisir_un_metier_value}--autre",
        ],
        if_subcategory_value="emploi--choisir-metier",
    )
    add_categories_and_subcategories_if_subcategory(
        ServiceCategory,
        ServiceSubCategory,
        Service,
        categories_value_to_add=["emploi-preparer-sa-candidature"],
        subcategory_value_to_add=[
            f"{emploi_preparer_sa_candidature_value}--valoriser-ses-competences",
            f"{emploi_preparer_sa_candidature_value}--realiser-un-cv-etou-une-lettre-de-motivation",
            f"{emploi_preparer_sa_candidature_value}--developper-son-reseau",
            f"{emploi_preparer_sa_candidature_value}--organiser-ses-demarches-de-recherche-demploi",
            f"{emploi_preparer_sa_candidature_value}--autre",
        ],
        if_subcategory_value="emploi--preparer-candidature",
    )
    add_categories_and_subcategories_if_subcategory(
        ServiceCategory,
        ServiceSubCategory,
        Service,
        categories_value_to_add=["emploi-trouver-emploi"],
        subcategory_value_to_add=[
            f"{emploi_trouver_un_emploi_value}--repondre-a-des-offres-demploi",
            f"{emploi_trouver_un_emploi_value}--faire-des-candidatures-spontanees",
            f"{emploi_trouver_un_emploi_value}--suivre-ses-candidatures-et-relancer-les-employeurs",
            f"{emploi_trouver_un_emploi_value}--convaincre-un-recruteur-en-entretien",
            f"{emploi_trouver_un_emploi_value}--autre",
        ],
        if_subcategory_value="emploi--trouver-emploi",
    )

    """
        3:
            Rattacher les services liés au besoin "emploi--autre" à toutes les thématiques et leur besoin "--autre"
    """
    add_categories_and_subcategories_if_subcategory(
        ServiceCategory,
        ServiceSubCategory,
        Service,
        categories_value_to_add=[
            emploi_trouver_un_emploi_value,
            emploi_preparer_sa_candidature_value,
            emploi_choisir_un_metier_value,
        ],
        subcategory_value_to_add=[
            f"{emploi_preparer_sa_candidature_value}--autre",
            f"{emploi_choisir_un_metier_value}--autre",
            f"{emploi_trouver_un_emploi_value}--autre",
        ],
        if_subcategory_value="emploi--autre",
    )

    """
        4: Délier la thématique "emploi" et les besoins "emploi--choisir-metier" "emploi--preparer-candidature" "emploi--trouver-emploi" aux services
    """
    emploi_value = "emploi"
    unlink_services_from_category(ServiceCategory, Service, category_value=emploi_value)
    unlink_services_from_subcategory(
        ServiceSubCategory,
        Service,
        subcategory_value=f"{emploi_value}--choisir-metier",
    )
    unlink_services_from_subcategory(
        ServiceSubCategory,
        Service,
        subcategory_value=f"{emploi_value}--preparer-candidature",
    )
    unlink_services_from_subcategory(
        ServiceSubCategory,
        Service,
        subcategory_value=f"{emploi_value}--trouver-emploi",
    )
    unlink_services_from_subcategory(
        ServiceSubCategory,
        Service,
        subcategory_value=f"{emploi_value}--autre",
    )

    """
        5: Supprimer la thématique "emploi" et les besoins "emploi--choisir-metier" "emploi--preparer-candidature" "emploi--trouver-emploi" "emploi--autre"
    """
    delete_category(ServiceCategory, emploi_value)
    delete_subcategory(ServiceSubCategory, f"{emploi_value}--choisir-metier")
    delete_subcategory(ServiceSubCategory, f"{emploi_value}--preparer-candidature")
    delete_subcategory(ServiceSubCategory, f"{emploi_value}--trouver-emploi")
    delete_subcategory(ServiceSubCategory, f"{emploi_value}--autre")


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0065_servicemodel_alter_service_numerique"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_options, reverse_code=migrations.RunPython.noop
        ),
    ]
