# Generated by Django 4.0.6 on 2022-07-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0066_servicemodel_alter_service_emploi"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomizableChoicesSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "access_conditions",
                    models.ManyToManyField(
                        blank=True,
                        to="services.accesscondition",
                        verbose_name="Critères d’admission",
                    ),
                ),
                (
                    "concerned_public",
                    models.ManyToManyField(
                        blank=True,
                        to="services.concernedpublic",
                        verbose_name="Publics concernés",
                    ),
                ),
                (
                    "credentials",
                    models.ManyToManyField(
                        blank=True,
                        to="services.credential",
                        verbose_name="Quels sont les justificatifs à fournir ?",
                    ),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        blank=True,
                        to="services.requirement",
                        verbose_name="Quels sont les pré-requis ou compétences ?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste de choix",
                "verbose_name_plural": "Listes de choix",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="customizable_choices_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.customizablechoicesset",
                verbose_name="Choix customisés",
            ),
        ),
    ]
