# Generated by Django 4.0.6 on 2022-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0068_alter_customizablechoicesset_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="moderation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEED_INITIAL_MODERATION", "Première modération nécessaire"),
                    ("NEED_NEW_MODERATION", "Nouvelle modération nécessaire"),
                    ("IN_PROGRESS", "En cours"),
                    ("VALIDATED", "Validé"),
                ],
                db_index=True,
                max_length=30,
                null=True,
                verbose_name="Modération",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
