# Generated by Django 4.0.6 on 2022-08-10 16:21

from django.conf import settings
from django.db import migrations

from dora.core.models import ModerationStatus

from ..enums import ServiceStatus


def init_moderation_status(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    LogItem = apps.get_model("core", "LogItem")
    User = apps.get_model("users", "User")

    services = Service.objects.filter(status=ServiceStatus.PUBLISHED)

    services.update(moderation_status=ModerationStatus.VALIDATED)
    msg = f"Modération initiale\nNouveau statut de modération : {ModerationStatus.VALIDATED.label}"
    bot_user = User.objects.get(email=settings.DORA_BOT_USER)
    for service in services:
        LogItem.objects.create(service=service, user=bot_user, message=msg)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("services", "0069_service_moderation_date_service_moderation_status_and_more"),
        ("users", "0005_create_dora_bot_user"),
    ]

    operations = [
        migrations.RunPython(
            init_moderation_status, reverse_code=migrations.RunPython.noop
        )
    ]
