# Generated by Django 4.0.6 on 2022-08-10 16:21

from django.db import migrations

from dora.core.models import ModerationStatus

from ..enums import ServiceStatus


def init_moderation_status(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    Service.objects.filter(status=ServiceStatus.PUBLISHED).update(
        moderation_status=ModerationStatus.VALIDATED
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0069_service_moderation_status_service_notes"),
    ]

    operations = [
        migrations.RunPython(
            init_moderation_status, reverse_code=migrations.RunPython.noop
        )
    ]
