# Generated by Django 4.0.6 on 2022-08-17 12:57

from django.db import migrations

from dora.services.migration_utils import (
    create_subcategory,
    delete_subcategory,
    replace_subcategory,
    update_subcategory_value_and_label,
)


def migrate_services_options(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    numerique_value = "numerique"

    # 1- Nouveaux besoins

    # 1.1- S’équiper en matériel informatique
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--sequiper-en-materiel-informatique",
        label="S’équiper en matériel informatique",
    )

    # 1.2- Créer avec le numérique
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--creer-avec-le-numerique",
        label="Créer avec le numérique",
    )

    # 1.3- Accompagner les démarches de santé
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--accompagner-les-demarches-de-sante",
        label="Accompagner les démarches de santé",
    )

    # 1.4- Promouvoir la citoyenneté numérique
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--promouvoir-la-citoyennete-numerique",
        label="Promouvoir la citoyenneté numérique",
    )

    # 1.5- Soutenir la parentalité et l’éducation avec le numérique
    create_subcategory(
        ServiceSubCategory,
        value=f"{numerique_value}--soutenir-la-parentalite-et-leducation-avec-le-numerique",
        label="Soutenir la parentalité et l’éducation avec le numérique",
    )

    # 2 Remplacement besoins
    # 2.1 - Gagner en autonomie dans les démarches administratives ⇒ Devenir autonome dans les démarches administratives
    update_subcategory_value_and_label(
        ServiceSubCategory,
        old_value=f"{numerique_value}--gagner-en-autonomie-dans-les-demarches-administratives",
        new_value=f"{numerique_value}--devenir-autonome-dans-les-demarches-administratives",
        new_label="Devenir autonome dans les démarches administratives",
    )

    # 2.2 - Etre accompagné dans les démarches administratives ⇒ Réaliser des démarches administratives avec un accompagnement
    update_subcategory_value_and_label(
        ServiceSubCategory,
        old_value=f"{numerique_value}--etre-accompagne-dans-les-demarches-administratives",
        new_value=f"{numerique_value}--realiser-des-demarches-administratives-avec-un-accompagnement",
        new_label="Réaliser des démarches administratives avec un accompagnement",
    )

    # 2.3 - Prendre en main un ordinateur ⇒ utiliser le numérique au quotidien
    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value=f"{numerique_value}--prendre-en-main-un-ordinateur",
        to_value=f"{numerique_value}--utiliser-le-numerique-au-quotidien",
    )
    delete_subcategory(
        ServiceSubCategory, f"{numerique_value}--prendre-en-main-un-ordinateur"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0072_service_can_update_category"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_options, reverse_code=migrations.RunPython.noop
        ),
    ]
