# Generated by Django 4.0.7 on 2022-09-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0073_update_numerique_subcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="can_update_categories",
            field=models.BooleanField(
                default=True,
                verbose_name="En tant que modèle, la mise à jour des thématiques est-elle possible ?",
            ),
        ),
    ]
