# Generated by Django 4.0.6 on 2022-08-17 12:57

from django.db import migrations

from dora.services.migration_utils import create_service_kind


def migrate_services_kind(apps, schema_editor):
    ServiceKind = apps.get_model("services", "ServiceKind")
    create_service_kind(ServiceKind, "numerique", "Service numérique")
    create_service_kind(ServiceKind, "autonomie", "En autonomie")
    create_service_kind(ServiceKind, "delegation", "Délégation")
    create_service_kind(ServiceKind, "financement", "Financement")


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0074_alter_service_can_update_categories"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_kind, reverse_code=migrations.RunPython.noop
        ),
    ]
