# Generated by Django 4.0.7 on 2022-09-19 14:01

from django.db import migrations


def migrate_fee(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceFee = apps.get_model("services", "ServiceFee")
    ServiceSuggestion = apps.get_model("service_suggestions", "ServiceSuggestion")

    free = ServiceFee.objects.filter(value="gratuit").first()
    not_free = ServiceFee.objects.filter(value="payant").first()

    # Migrate service => has_fee ? "payant" : "gratuit"
    for service in Service.objects.all():
        service.fee_condition = not_free if service.has_fee else free
        service.save(update_fields=["fee_condition"])

    # Migrate service suggestion
    for s in ServiceSuggestion.objects.all():
        has_fee = s.contents.pop("has_fee", False)
        s.contents["fee_condition"] = "payant" if has_fee else "gratuit"
        s.save(update_fields=["contents"])


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0076_servicefee_service_fee_condition"),
    ]

    operations = [
        migrations.RunPython(migrate_fee, reverse_code=migrations.RunPython.noop),
    ]
