# Generated by Django 4.0.7 on 2022-09-19 14:01

from django.db import migrations

from dora.services.migration_utils import (
    create_subcategory,
    delete_subcategory,
    replace_subcategory,
)

SUBSTITUTIONS = {
    "mobilite--identifier-freins": "mobilite--accompagnement-parcours-mobilite",
}


def migrate_categories(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")
    ServiceSuggestion = apps.get_model("service_suggestions", "ServiceSuggestion")

    # Création d'activité
    create_subcategory(
        ServiceSubCategory,
        value="creation-activite--developper-son-entreprise",
        label="Développer son entreprise",
    )

    # Mobilité
    # => Ajouter “Financer mon projet mobilité”
    create_subcategory(
        ServiceSubCategory,
        value="mobilite--financer-mon-projet-mobilite",
        label="Financer mon projet mobilité",
    )

    # => Fusionner “Identifier ses freins, et définir ses besoins en mobilité” avec “Etre accompagné(e) dans son parcours mobilité”
    replace_subcategory(
        ServiceSubCategory,
        Service,
        from_value="mobilite--identifier-freins",
        to_value="mobilite--accompagnement-parcours-mobilite",
    )
    delete_subcategory(ServiceSubCategory, "mobilite--identifier-freins")

    for s in ServiceSuggestion.objects.all():
        subcats = list(s.contents["subcategories"])
        subcats = list(set(SUBSTITUTIONS.get(value, value) for value in subcats))
        s.contents["subcategories"] = subcats
        s.save(update_fields=["contents"])


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0077_migrate_fee"),
    ]

    operations = [
        migrations.RunPython(
            migrate_categories, reverse_code=migrations.RunPython.noop
        ),
    ]
