# Generated by Django 4.0.7 on 2022-10-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0078_migrate_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="fee_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.servicefee",
                verbose_name="Frais à charge",
            ),
        ),
    ]
