# Generated by Django 4.0.8 on 2022-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0079_alter_service_fee_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="use_inclusion_numerique_scheme",
            field=models.BooleanField(default=False),
        ),
    ]
