# Generated by Django 4.0.8 on 2022-10-24 16:08

from django.db import migrations


def add_fee_conditions(apps, schema_editor):
    ServiceFee = apps.get_model("services", "ServiceFee")
    ServiceFee.objects.create(value="pass-numerique", label="Accepte le pass numérique")


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0080_service_use_inclusion_numerique_scheme"),
    ]

    operations = [
        migrations.RunPython(
            add_fee_conditions, reverse_code=migrations.RunPython.noop
        ),
    ]
