# Generated by Django 4.0.8 on 2022-10-24 16:08

from django.db import migrations


def add_subcategories(apps, schema_editor):
    ConcernedPublic = apps.get_model("services", "ConcernedPublic")

    ConcernedPublic.objects.create(name="Personnes en situation d’illettrisme")
    ConcernedPublic.objects.create(name="Femmes")
    ConcernedPublic.objects.create(name="Adultes")

    ConcernedPublic.objects.filter(name="Famille/enfants").update(
        name="Familles/enfants"
    )
    ConcernedPublic.objects.filter(
        name="Handicaps mentaux : déficiences limitant les activités d'une personne"
    ).update(
        name="Handicaps mentaux : déficiences limitant les activités d’une personne"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0082_new_subcategories"),
    ]

    operations = [
        migrations.RunPython(add_subcategories, reverse_code=migrations.RunPython.noop),
    ]
