# Generated by Django 4.1.3 on 2022-12-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0084_bookmark_bookmark_services_unique_bookmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="last_draft_notification_date",
        ),
    ]
