# Generated by Django 4.1.3 on 2023-01-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0085_remove_service_last_draft_notification_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="filling_duration",
        ),
    ]
