# Generated by Django 4.1.3 on 2023-01-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0086_remove_service_filling_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="can_update_categories",
        ),
        migrations.RemoveField(
            model_name="service",
            name="customizable_choices_set",
        ),
        migrations.DeleteModel(
            name="CustomizableChoicesSet",
        ),
    ]
