# Generated by Django 4.0.6 on 2022-08-17 12:57

from django.db import migrations

from dora.services.migration_utils import (
    create_subcategory,
    update_category_value_and_label,
)


def migrate_services_options(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    # Accès aux droits & citoyenneté
    create_subcategory(
        ServiceSubCategory,
        value="acces-aux-droits--developpement-durable",
        label="Développement durable",
    )
    create_subcategory(
        ServiceSubCategory,
        value="acces-aux-droits--faciliter-laction-citoyenne",
        label="Faciliter l'action citoyenne",
    )

    # Acco. global individualisé -- Accompagnement social et professionnel personnalisé
    update_category_value_and_label(
        ServiceCategory,
        old_value="acc-global-indiv",
        new_value="accompagnement-social-et-professionnel-personnalise",
        new_label="Accompagnement social et professionnel personnalisé",
    )

    # Création d'activité
    create_subcategory(
        ServiceSubCategory,
        value="creation-activite--developper-son-entreprise",
        label="Développer son entreprise",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0086_remove_service_can_update_categories_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_options, reverse_code=migrations.RunPython.noop
        ),
    ]
