# Generated by Django 4.0.6 on 2022-08-17 12:57

from django.db import migrations

from dora.services.migration_utils import update_subcategory_value_and_label


def migrate_services_options(apps, schema_editor):
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    # Acco. global individualisé => Accompagnement social et professionnel personnalisé
    update_subcategory_value_and_label(
        ServiceSubCategory,
        "acc-global-indiv--autre",
        "accompagnement-social-et-professionnel-personnalise--autre",
        "Autre",
    )
    update_subcategory_value_and_label(
        ServiceSubCategory,
        "acc-global-indiv--decrochage-scolaire",
        "accompagnement-social-et-professionnel-personnalise--decrochage-scolaire",
        "Décrochage scolaire",
    )
    update_subcategory_value_and_label(
        ServiceSubCategory,
        "acc-global-indiv--definition-projet-pro",
        "accompagnement-social-et-professionnel-personnalise--definition-projet-pro",
        "Définition du projet professionnel",
    )
    update_subcategory_value_and_label(
        ServiceSubCategory,
        "acc-global-indiv--parcours-insertion-sociopro",
        "accompagnement-social-et-professionnel-personnalise--parcours-insertion-sociopro",
        "Parcours d’insertion socio-professionnel",
    )

    # Difficultes financières - Autre => Gestion financière - Autre
    update_subcategory_value_and_label(
        ServiceSubCategory,
        "difficultes-financieres--autre",
        "gestion-financiere--autre",
        "Autre",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0087_update_categories_and_subcategories"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_options, reverse_code=migrations.RunPython.noop
        ),
    ]
