# Generated by Django 4.1.7 on 2023-04-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0090_update_categories_and_subcategories_ter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Source",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="data_inclusion_id",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name="service",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.servicesource",
            ),
        ),
    ]
