# Generated by Django 4.0.6 on 2022-08-17 12:57

from django.db import migrations

from dora.services.migration_utils import rename_subcategory


def migrate_services_options(apps, schema_editor):
    ServiceSubCategory = apps.get_model("services", "ServiceSubCategory")

    rename_subcategory(
        ServiceSubCategory,
        "sante--diagnostic-et-accompagnement-a-lemployabilite",
        "Diagnostic et accompagnement à l'employabilité",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0090_update_categories_and_subcategories_ter"),
    ]

    operations = [
        migrations.RunPython(
            migrate_services_options, reverse_code=migrations.RunPython.noop
        ),
    ]
