# Generated by Django 4.1.7 on 2023-05-04 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0091_servicesource_service_data_inclusion_id_and_more"),
        ("services", "0091_update_categories_and_subcategories_fix"),
    ]

    operations = []
