# Generated by Django 4.1.9 on 2023-05-16 14:25

from django.db import migrations

from dora.admin_express.utils import get_clean_city_name
from dora.core.utils import code_insee_to_code_dept


def clean_city_names(apps, _):
    Service = apps.get_model("services", "Service")
    Service.objects.all().update(city="")
    for service in Service.objects.exclude(city_code=""):
        service.city = get_clean_city_name(service.city_code)
        service.department = code_insee_to_code_dept(service.city_code)
        service.save()


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0092_merge_20230504_1731"),
    ]

    operations = [
        migrations.RunPython(clean_city_names, reverse_code=migrations.RunPython.noop),
    ]
