# Generated by Django 4.1.9 on 2023-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0093_clean_city-names"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="data_inclusion_source",
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
