# Generated by Django 4.1.9 on 2023-06-09 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0094_service_data_inclusion_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_draft",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_suggestion",
        ),
    ]
