# Generated by Django 4.2.3 on 2023-08-21 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_frequency_alert(apps, _):
    AlertFrequency = apps.get_model("services", "AlertFrequency")
    AlertFrequency.objects.create(value="never", label="Jamais")
    AlertFrequency.objects.create(value="two-weeks", label="Toutes les deux semaines")
    AlertFrequency.objects.create(value="monthly", label="Chaque mois")


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0095_remove_service_is_draft_remove_service_is_suggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Fréquence de l'alerte",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "city_code",
                    models.CharField(verbose_name="Code INSEE de la recherche"),
                ),
                ("city_label", models.CharField(verbose_name="Label de la ville")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        to="services.servicecategory",
                        verbose_name="Thématiques",
                    ),
                ),
                (
                    "fees",
                    models.ManyToManyField(
                        blank=True,
                        to="services.servicefee",
                        verbose_name="Frais à charge",
                    ),
                ),
                (
                    "frequency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.alertfrequency",
                        verbose_name="Fréquence de l'alerte",
                    ),
                ),
                (
                    "kinds",
                    models.ManyToManyField(
                        blank=True,
                        to="services.servicekind",
                        verbose_name="Type de service",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True,
                        to="services.servicesubcategory",
                        verbose_name="Besoins",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            add_frequency_alert, reverse_code=migrations.RunPython.noop
        ),
    ]
