# Generated by Django 4.2.3 on 2023-10-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0096_savedsearch"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="services_unique_bookmark",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="di_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
            ),
        ),
    ]
