# Generated by Django 4.2.3 on 2023-09-19 08:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0096_savedsearchfrequency_savedsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="last_notification_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
