# Generated by Django 4.2.7 on 2023-12-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0098_add_them_seformer_internat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedsearch",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.servicecategory",
                verbose_name="Thématique",
            ),
        ),
    ]
