# Generated by Django 4.2.7 on 2024-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0099_alter_savedsearch_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="recurrence",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="Récurrence"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="suspension_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Jusqu’au"
            ),
        ),
    ]
