# Generated by Django 4.2.7 on 2024-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0100_alter_service_recurrence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="di_id",
            field=models.TextField(blank=True),
        ),
    ]
