# Generated by Django 4.2.7 on 2024-02-08 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0101_alter_bookmark_di_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="has_fee",
        ),
    ]
