# Generated by Django 4.2.7 on 2024-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0102_remove_service_has_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="location_kinds",
            field=models.ManyToManyField(
                blank=True,
                to="services.locationkind",
                verbose_name="Lieu de déroulement",
            ),
        ),
    ]
