# Generated by Django 4.2.12 on 2024-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0106_service_coach_orientation_modes_external_form_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="beneficiaries_access_modes_external_form_link",
            field=models.URLField(
                blank=True, verbose_name="Lien vers le formulaire externe"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="beneficiaries_access_modes_external_form_link_text",
            field=models.CharField(
                blank=True,
                max_length=27,
                verbose_name="L’intitulé du lien vers le formulaire externe",
            ),
        ),
    ]
