# Generated by Django 4.2.12 on 2024-07-31 13:05

from django.db import migrations


def rename_orientation_mode_label(apps, schema_editor, reverse):
    # Récupération des modèles des modes d'orientation
    CoachOrientationMode = apps.get_model("services", "CoachOrientationMode")
    BeneficiaryAccessMode = apps.get_model("services", "BeneficiaryAccessMode")

    # Nouveau label
    new_label = (
        "Via notre propre formulaire/site internet"
        if reverse
        else "Via notre propre formulaire en ligne/site internet"
    )

    # Renommage des labels des modes d'orientation
    CoachOrientationMode.objects.filter(
        value="completer-le-formulaire-dadhesion"
    ).update(label=new_label)
    BeneficiaryAccessMode.objects.filter(
        value="completer-le-formulaire-dadhesion"
    ).update(label=new_label)


def migration(apps, schema_editor):
    rename_orientation_mode_label(apps, schema_editor, False)


def migration_reverse(apps, schema_editor):
    rename_orientation_mode_label(apps, schema_editor, True)


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0108_align_orientation_modes_with_di",
        ),
    ]

    operations = [
        migrations.RunPython(migration, reverse_code=migration_reverse),
    ]
