# Generated by Django 4.2.15 on 2024-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0109_rename_orientation_mode_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        db_index=True, max_length=3, verbose_name="département"
                    ),
                ),
                ("label", models.CharField(verbose_name="label")),
            ],
            options={
                "verbose_name": "label de financement",
                "verbose_name_plural": "labels de financement",
            },
        ),
    ]
