# Generated by Django 4.2.15 on 2024-08-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0110_fundinglabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="funding_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.fundinglabel",
            ),
        ),
    ]
