# Generated by Django 4.2.15 on 2024-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0110_remove_service_fee_pass_numerique"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="spending_time_precision",
            field=models.CharField(
                blank=True,
                max_length=60,
                verbose_name="Précision sur la répartition du temps passé",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="spending_time_total_hours",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Temps passé (total des heures passées par le bénéficiaire)",
            ),
        ),
    ]
